<?php

namespace Modules\Admin\Database\Seeders;

use Illuminate\Database\Seeder;

class CustomersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('customers')->delete();

        \DB::table('customers')->insert(array(
            0 => array(
                'id' => 1,
                'project_number' => '1224567',
                'client_name' => 'Google',
                'contact_person_name' => 'Larry Page',
                'contact_person_email_id' => 'test1@mail.com',
                'contact_person_phone' => '(444)444-4444',
                'contact_person_position' => 'SVP-COO',
                'requester_name' => 'Renea Mattis',
                'requester_position' => 'Larry Page',
                'requester_empno' => '123456',
                'address' => '2947 Portland Drive',
                'city' => 'Oakville',
                'province' => 'Oakville',
                'postal_code' => 'M4T2Y8',
                'geo_location_lat' => '43.6883412',
                'geo_location_long' => '-79.3935153',
                'radius' => null,
                'active' => 1,
                'description' => 'General Job Posting',
                'proj_open' => '2017-12-08',
                'arpurchase_order_no' => '1',
                'arcust_type' => '2',
                'stc' => 1,
                'inquiry_date' => null,
                'time_stamp' => null,
                'duty_officer_id' => '1',
                'industry_sector_lookup_id' => '2',
                'region_lookup_id' => '1',
                'guard_tour_enabled' => 0,
                'guard_tour_duration' => null,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            1 => array(
                'id' => 2,
                'project_number' => '7000000',
                'client_name' => 'Commissionaires - Spares',
                'contact_person_name' => 'Ben Alexander',
                'contact_person_email_id' => 'test2@mail.com',
                'contact_person_phone' => '(644)480-7844',
                'contact_person_position' => 'SVP-COO',
                'requester_name' => 'Benjamin Alexander',
                'requester_position' => 'Area Manager',
                'requester_empno' => '123346780',
                'address' => '300 Dufferin Street',
                'city' => 'London',
                'province' => 'London',
                'postal_code' => 'M6P2K7',
                'geo_location_lat' => '43.6644181',
                'geo_location_long' => '-79.4668284',
                'radius' => null,
                'active' => 1,
                'description' => 'General Job Posting',
                'proj_open' => '2017-11-12',
                'arpurchase_order_no' => '1',
                'arcust_type' => '2',
                'stc' => 1,
                'inquiry_date' => null,
                'time_stamp' => null,
                'duty_officer_id' => '1',
                'industry_sector_lookup_id' => '3',
                'region_lookup_id' => '2',
                'guard_tour_enabled' => 0,
                'guard_tour_duration' => null,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            2 => array(
                'id' => 3,
                'project_number' => '1003787',
                'client_name' => 'Wynford Condo - MTCC 577',
                'contact_person_name' => 'Darnel Somers',
                'contact_person_email_id' => 'test3@mail.com',
                'contact_person_phone' => '(416)447-3464',
                'contact_person_position' => 'SVP-COO',
                'requester_name' => 'Renea Mattis',
                'requester_position' => 'Area Manager',
                'requester_empno' => null,
                'address' => '75 Wynford Heights Crescent',
                'city' => 'North York',
                'province' => 'London',
                'postal_code' => 'M3C3H9',
                'geo_location_lat' => '43.7285804',
                'geo_location_long' => '-79.3281618',
                'radius' => null,
                'active' => 1,
                'description' => 'Condominimum.  One SU and one CM.  Bill rate is $21.08.  SU rate is $15.27 and CM is $14.24.  They are entitled to 2% increase on January  2018.',
                'proj_open' => '2017-12-08',
                'arpurchase_order_no' => null,
                'arcust_type' => null,
                'stc' => 0,
                'inquiry_date' => null,
                'time_stamp' => null,
                'duty_officer_id' => '1',
                'industry_sector_lookup_id' => '3',
                'region_lookup_id' => '2',
                'guard_tour_enabled' => 0,
                'guard_tour_duration' => null,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => '2017-12-08 16:41:36',
                'updated_at' => '2017-12-08 16:41:36',
                'deleted_at' => null,
            ),
            3 => array(
                'id' => 4,
                'project_number' => '6000001',
                'client_name' => 'Commissionaires Great lakes',
                'contact_person_name' => 'Benjamin Alexander',
                'contact_person_email_id' => 'test4@mail.com',
                'contact_person_phone' => '(416)802-5559',
                'contact_person_position' => 'SVP-COO',
                'requester_name' => 'Benjamin Alexander',
                'requester_position' => 'SVP-COO',
                'requester_empno' => '122514',
                'address' => '2947 Portland Drive',
                'city' => 'Ottawa',
                'province' => 'Canada',
                'postal_code' => 'K1A0B1',
                'geo_location_lat' => '45.3746',
                'geo_location_long' => '75.6902',
                'radius' => null,
                'active' => 1,
                'description' => 'Headquarters',
                'proj_open' => '2017-12-08',
                'arpurchase_order_no' => null,
                'arcust_type' => null,
                'stc' => 0,
                'inquiry_date' => null,
                'time_stamp' => null,
                'duty_officer_id' => '1',
                'industry_sector_lookup_id' => '3',
                'region_lookup_id' => '2',
                'guard_tour_enabled' => 0,
                'guard_tour_duration' => null,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => '2017-12-08 18:47:03',
                'updated_at' => '2017-12-08 18:47:03',
                'deleted_at' => null,
            ),
        ));
    }
}
