<?php

namespace Modules\Admin\Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class EmailNotificationHelperSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('email_notification_helpers')->delete();

        \DB::table('email_notification_helpers')->insert(array(
            0 => array(
                'id' => 1,
                'email_notification_type_id' => null,
                'replace_string' => '{client}',
                'replace_value' => 'Client name',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            1 => array(
                'id' => 2,
                'email_notification_type_id' => null,
                'replace_string' => '{projectNumber}',
                'replace_value' => 'Project number',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            2 => array(
                'id' => 3,
                'email_notification_type_id' => null,
                'replace_string' => '{loggedInUser}',
                'replace_value' => 'Logged in user',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            3 => array(
                'id' => 4,
                'email_notification_type_id' => null,
                'replace_string' => '{loggedInUserEmployeeNumber}',
                'replace_value' => 'Logged in user employee number',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            4 => array(
                'id' => 5,
                'email_notification_type_id' => null,
                'replace_string' => '{receiverFullName}',
                'replace_value' => 'Receiver full name',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            5 => array(
                'id' => 6,
                'email_notification_type_id' => 1,
                'replace_string' => '{severity}',
                'replace_value' => 'Client concern severity',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            6 => array(
                'id' => 7,
                'email_notification_type_id' => 2,
                'replace_string' => '{rating}',
                'replace_value' => 'Client feedback rating',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            7 => array(
                'id' => 8,
                'email_notification_type_id' => 3,
                'replace_string' => '{vehicleNumber}',
                'replace_value' => 'Vehicle number',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            8 => array(
                'id' => 9,
                'email_notification_type_id' => 3,
                'replace_string' => '{maintenanceDetails}',
                'replace_value' => 'Maintenance details',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            9 => array(
                'id' => 10,
                'email_notification_type_id' => 4,
                'replace_string' => '{vehicleNumber}',
                'replace_value' => 'Vehicle number',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            10 => array(
                'id' => 11,
                'email_notification_type_id' => 4,
                'replace_string' => '{maintenanceDetails}',
                'replace_value' => 'Maintenance details',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            12 => array(
                'id' => 13,
                'email_notification_type_id' => 5,
                'replace_string' => '{thresholdexceededlist}',
                'replace_value' => 'Schedule weekly/bi-weekly threshold exceeded employee list',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            13 => array(
                'id' => 14,
                'email_notification_type_id' => 6,
                'replace_string' => '{scheduleStatus}',
                'replace_value' => 'Schedule status',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            14 => array(
                'id' => 15,
                'email_notification_type_id' => 6,
                'replace_string' => '{scheduleReasonNote}',
                'replace_value' => 'Schedule reject reason note',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            15 => array(
                'id' => 16,
                'email_notification_type_id' => 4,
                'replace_string' => '{region}',
                'replace_value' => 'Region',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            16 => array(
                'id' => 17,
                'email_notification_type_id' => 3,
                'replace_string' => '{region}',
                'replace_value' => 'Region',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            17 => array(
                'id' => 18,
                'email_notification_type_id' => 8,
                'replace_string' => '{projectName}',
                'replace_value' => 'Project name',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            18 => array(
                'id' => 19,
                'email_notification_type_id' => 8,
                'replace_string' => '{groupName}',
                'replace_value' => 'Group name',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            19 => array(
                'id' => 20,
                'email_notification_type_id' => 8,
                'replace_string' => '{taskName}',
                'replace_value' => 'Task name',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            20 => array(
                'id' => 21,
                'email_notification_type_id' => 8,
                'replace_string' => '{dueInDays}',
                'replace_value' => 'Due in days',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            21 => array(
                'id' => 22,
                'email_notification_type_id' => 8,
                'replace_string' => '{dueDate}',
                'replace_value' => 'Due date',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            22 => array(
                'id' => 23,
                'email_notification_type_id' => 8,
                'replace_string' => '{taskUrl}',
                'replace_value' => 'Task URL',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            23 => array(
                'id' => 24,
                'email_notification_type_id' => 9,
                'replace_string' => '{projectName}',
                'replace_value' => 'Project name',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            24 => array(
                'id' => 25,
                'email_notification_type_id' => 9,
                'replace_string' => '{groupName}',
                'replace_value' => 'Group name',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            25 => array(
                'id' => 26,
                'email_notification_type_id' => 9,
                'replace_string' => '{taskName}',
                'replace_value' => 'Task name',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            26 => array(
                'id' => 27,
                'email_notification_type_id' => 9,
                'replace_string' => '{dueInDays}',
                'replace_value' => 'Due in days',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            27 => array(
                'id' => 28,
                'email_notification_type_id' => 9,
                'replace_string' => '{dueDate}',
                'replace_value' => 'Due date',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            29 => array(
                'id' => 30,
                'email_notification_type_id' => 9,
                'replace_string' => '{reportUrl}',
                'replace_value' => 'Report URL',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            30 => array(
                'id' => 31,
                'email_notification_type_id' => 10,
                'replace_string' => '{trackingURL}',
                'replace_value' => 'Client onboarding tracking URL',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            31 => array(
                'id' => 32,
                'email_notification_type_id' => 10,
                'replace_string' => '{targetDate}',
                'replace_value' => 'Target date of onboarding task',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            32 => array(
                'id' => 33,
                'email_notification_type_id' => 10,
                'replace_string' => '{step}',
                'replace_value' => 'Step - task title',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            33 => array(
                'id' => 34,
                'email_notification_type_id' => 11,
                'replace_string' => '{trackingURL}',
                'replace_value' => 'Client onboarding tracking URL',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            34 => array(
                'id' => 35,
                'email_notification_type_id' => 11,
                'replace_string' => '{targetDate}',
                'replace_value' => 'Target date of onboarding task',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            35 => array(
                'id' => 36,
                'email_notification_type_id' => 11,
                'replace_string' => '{step}',
                'replace_value' => 'Step - task title',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            36 => array(
                'id' => 37,
                'email_notification_type_id' => 12,
                'replace_string' => '{projectName}',
                'replace_value' => 'Project name',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            37 => array(
                'id' => 38,
                'email_notification_type_id' => 12,
                'replace_string' => '{groupName}',
                'replace_value' => 'Group name',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            38 => array(
                'id' => 39,
                'email_notification_type_id' => 12,
                'replace_string' => '{taskName}',
                'replace_value' => 'Task name',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            39 => array(
                'id' => 40,
                'email_notification_type_id' => 12,
                'replace_string' => '{dueInDays}',
                'replace_value' => 'Due in days',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            40 => array(
                'id' => 41,
                'email_notification_type_id' => 12,
                'replace_string' => '{dueDate}',
                'replace_value' => 'Due date',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            41 => array(
                'id' => 42,
                'email_notification_type_id' => 13,
                'replace_string' => '{projectName}',
                'replace_value' => 'Project name',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            42 => array(
                'id' => 43,
                'email_notification_type_id' => 13,
                'replace_string' => '{groupName}',
                'replace_value' => 'Group name',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            43 => array(
                'id' => 44,
                'email_notification_type_id' => 13,
                'replace_string' => '{taskName}',
                'replace_value' => 'Task name',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            44 => array(
                'id' => 45,
                'email_notification_type_id' => 13,
                'replace_string' => '{dueInDays}',
                'replace_value' => 'Due in days',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            45 => array(
                'id' => 46,
                'email_notification_type_id' => 13,
                'replace_string' => '{dueDate}',
                'replace_value' => 'Due date',
                'created_at' => '2019-01-03 18:30:00',
                'updated_at' => '2019-01-03 18:30:00',
                'deleted_at' => null,
            ),
            46 => array(
                'id' => 47,
                'email_notification_type_id' => 14,
                'replace_string' => '{expiredUserCertificateName}',
                'replace_value' => 'Certificate name',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            47 => array(
                'id' => 48,
                'email_notification_type_id' => 14,
                'replace_string' => '{userCertificateExpiryDate}',
                'replace_value' => 'Certificate expiry date',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            48 => array(
                'id' => 49,
                'email_notification_type_id' => 14,
                'replace_string' => '{userCertificateExpiryDueInDays}',
                'replace_value' => 'Certificate expiry in days',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            49 => array(
                'id' => 50,
                'email_notification_type_id' => 15,
                'replace_string' => '{expiredUserCertificateName}',
                'replace_value' => 'Certificate name',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            50 => array(
                'id' => 51,
                'email_notification_type_id' => 15,
                'replace_string' => '{userCertificateExpiryDate}',
                'replace_value' => 'Certificate expiry date',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            51 => array(
                'id' => 52,
                'email_notification_type_id' => 15,
                'replace_string' => '{userCertificateExpiryDueInDays}',
                'replace_value' => 'Certificate expiry in days',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            52 => array(
                'id' => 53,
                'email_notification_type_id' => 16,
                'replace_string' => '{expiredUserCertificateName}',
                'replace_value' => 'Expired/Expiring User Certificate name',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            53 => array(
                'id' => 54,
                'email_notification_type_id' => 16,
                'replace_string' => '{userCertificateExpiryDate}',
                'replace_value' => 'Certificate expiry date',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            54 => array(
                'id' => 55,
                'email_notification_type_id' => 16,
                'replace_string' => '{userCertificateExpiryDueInDays}',
                'replace_value' => 'Certificate expiry in days',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            55 => array(
                'id' => 56,
                'email_notification_type_id' => 17,
                'replace_string' => '{expiredUserCertificateName}',
                'replace_value' => 'Expired/Expire User Certificate name',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            56 => array(
                'id' => 57,
                'email_notification_type_id' => 17,
                'replace_string' => '{userCertificateExpiryDate}',
                'replace_value' => 'Certificate expiry date',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            57 => array(
                'id' => 58,
                'email_notification_type_id' => 17,
                'replace_string' => '{userCertificateExpiryDueInDays}',
                'replace_value' => 'Certificate expiry in days',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            58 => array(
                'id' => 59,
                'email_notification_type_id' => 18,
                'replace_string' => '{submittedByEmployeeName}',
                'replace_value' => 'Expense submitted employee',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            59 => array(
                'id' => 60,
                'email_notification_type_id' => 18,
                'replace_string' => '{submittedByEmployeeNumber}',
                'replace_value' => 'Expense submitted employee number',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            60 => array(
                'id' => 61,
                'email_notification_type_id' => 18,
                'replace_string' => '{submittedDate}',
                'replace_value' => 'Expense submitted date',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            61 => array(
                'id' => 62,
                'email_notification_type_id' => 18,
                'replace_string' => '{totalAmount}',
                'replace_value' => 'Total Amount',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            62 => array(
                'id' => 63,
                'email_notification_type_id' => 23,
                'replace_string' => '{candidateScheduleShiftStartDate}',
                'replace_value' => 'Allocated candidate schedule shift start date',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            63 => array(
                'id' => 64,
                'email_notification_type_id' => 23,
                'replace_string' => '{candidateScheduleShiftEndDate}',
                'replace_value' => 'Allocated candidate schedule shift end date',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            64 => array(
                'id' => 65,
                'email_notification_type_id' => 24,
                'replace_string' => '{candidateScheduleShiftStartDate}',
                'replace_value' => 'Un-allocated candidate schedule shift start date',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            65 => array(
                'id' => 66,
                'email_notification_type_id' => 24,
                'replace_string' => '{candidateScheduleShiftEndDate}',
                'replace_value' => 'Un-allocated candidate schedule shift end date',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            66 => array(
                'id' => 67,
                'email_notification_type_id' => 25,
                'replace_string' => '{candidateScheduleShiftStartDate}',
                'replace_value' => 'Removed candidate schedule shift start date',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            67 => array(
                'id' => 68,
                'email_notification_type_id' => 23,
                'replace_string' => '{candidateScheduleShiftStatus}',
                'replace_value' => 'Candidate schedule shift assigned status',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            68 => array(
                'id' => 69,
                'email_notification_type_id' => 23,
                'replace_string' => '{candidateScheduleShiftStatusNote}',
                'replace_value' => 'Candidate schedule shift assigned status note',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            69 => array(
                'id' => 70,
                'email_notification_type_id' => 28,
                'replace_string' => '{candidateScheduleShiftStartDate}',
                'replace_value' => 'Candidate Open shift start date',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            70 => array(
                'id' => 71,
                'email_notification_type_id' => 28,
                'replace_string' => '{candidateScheduleShiftEndDate}',
                'replace_value' => 'Candidate Open shift end date',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            71 => array(
                'id' => 72,
                'email_notification_type_id' => 28,
                'replace_string' => '{candidateScheduleShiftStartTime}',
                'replace_value' => 'Candidate Open shift start time',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            72 => array(
                'id' => 73,
                'email_notification_type_id' => 28,
                'replace_string' => '{candidateScheduleShiftEndTime}',
                'replace_value' => 'Candidate Open shift end time',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            73 => array(
                'id' => 74,
                'email_notification_type_id' => 23,
                'replace_string' => '{candidateScheduleSiteRate}',
                'replace_value' => 'Site Rate/Accepted Rate',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            74 => array(
                'id' => 75,
                'email_notification_type_id' => 23,
                'replace_string' => '{candidateScheduleNoOfShifts}',
                'replace_value' => 'Number of Positions',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            75 => array(
                'id' => 76,
                'email_notification_type_id' => 23,
                'replace_string' => '{candidateScheduleShiftTiming}',
                'replace_value' => 'Shift Timing',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            76 => array(
                'id' => 77,
                'email_notification_type_id' => 23,
                'replace_string' => '{candidateScheduleSiteAddress}',
                'replace_value' => 'Site Address',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            77 => array(
                'id' => 78,
                'email_notification_type_id' => 23,
                'replace_string' => '{candidateScheduleCity}',
                'replace_value' => 'City',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            78 => array(
                'id' => 79,
                'email_notification_type_id' => 23,
                'replace_string' => '{candidateSchedulePostalCode}',
                'replace_value' => 'Postal Code',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            79 => array(
                'id' => 80,
                'email_notification_type_id' => 23,
                'replace_string' => '{candidateScheduleAssignmentType}',
                'replace_value' => 'Assignment Type',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            80 => array(
                'id' => 81,
                'email_notification_type_id' => 24,
                'replace_string' => '{candidateScheduleSiteRate}',
                'replace_value' => 'Site Rate/Accepted Rate',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            81 => array(
                'id' => 82,
                'email_notification_type_id' => 24,
                'replace_string' => '{candidateScheduleNoOfShifts}',
                'replace_value' => 'Number of Positions',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            82 => array(
                'id' => 83,
                'email_notification_type_id' => 24,
                'replace_string' => '{candidateScheduleShiftTiming}',
                'replace_value' => 'Shift Timing',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            83 => array(
                'id' => 84,
                'email_notification_type_id' => 24,
                'replace_string' => '{candidateScheduleSiteAddress}',
                'replace_value' => 'Site Address',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            84 => array(
                'id' => 85,
                'email_notification_type_id' => 24,
                'replace_string' => '{candidateScheduleCity}',
                'replace_value' => 'City',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            85 => array(
                'id' => 86,
                'email_notification_type_id' => 24,
                'replace_string' => '{candidateSchedulePostalCode}',
                'replace_value' => 'Post Code',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            86 => array(
                'id' => 87,
                'email_notification_type_id' => 24,
                'replace_string' => '{candidateScheduleAssignmentType}',
                'replace_value' => 'Assignment Type',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            87 => array(
                'id' => 88,
                'email_notification_type_id' => 25,
                'replace_string' => '{candidateScheduleShiftEndTime}',
                'replace_value' => 'Removed candidate schedule shift start end time',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            88 => array(
                'id' => 89,
                'email_notification_type_id' => 25,
                'replace_string' => '{candidateScheduleSiteRate}',
                'replace_value' => 'Site Rate/Accepted Rate',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            89 => array(
                'id' => 90,
                'email_notification_type_id' => 25,
                'replace_string' => '{candidateScheduleNoOfShifts}',
                'replace_value' => 'Number of Positions',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            90 => array(
                'id' => 91,
                'email_notification_type_id' => 25,
                'replace_string' => '{candidateScheduleShiftTiming}',
                'replace_value' => 'Shift Timing',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            91 => array(
                'id' => 92,
                'email_notification_type_id' => 25,
                'replace_string' => '{candidateScheduleSiteAddress}',
                'replace_value' => 'Site Address',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            92 => array(
                'id' => 93,
                'email_notification_type_id' => 25,
                'replace_string' => '{candidateScheduleCity}',
                'replace_value' => 'City',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            93 => array(
                'id' => 94,
                'email_notification_type_id' => 25,
                'replace_string' => '{candidateSchedulePostalCode}',
                'replace_value' => 'Post Code',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            94 => array(
                'id' => 95,
                'email_notification_type_id' => 25,
                'replace_string' => '{candidateScheduleAssignmentType}',
                'replace_value' => 'Assignment Type',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            95 => array(
                'id' => 96,
                'email_notification_type_id' => 28,
                'replace_string' => '{candidateScheduleSiteRate}',
                'replace_value' => 'Site Rate/Accepted Rate',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            96 => array(
                'id' => 97,
                'email_notification_type_id' => 28,
                'replace_string' => '{candidateScheduleNoOfShifts}',
                'replace_value' => 'Number of Positions',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            97 => array(
                'id' => 98,
                'email_notification_type_id' => 28,
                'replace_string' => '{candidateScheduleShiftTiming}',
                'replace_value' => 'Shift Timing',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            98 => array(
                'id' => 99,
                'email_notification_type_id' => 28,
                'replace_string' => '{candidateScheduleSiteAddress}',
                'replace_value' => 'Site Address',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            99 => array(
                'id' => 100,
                'email_notification_type_id' => 28,
                'replace_string' => '{candidateScheduleCity}',
                'replace_value' => 'City',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            100 => array(
                'id' => 101,
                'email_notification_type_id' => 28,
                'replace_string' => '{candidateSchedulePostalCode}',
                'replace_value' => 'Post Code',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            101 => array(
                'id' => 102,
                'email_notification_type_id' => 28,
                'replace_string' => '{candidateScheduleAssignmentType}',
                'replace_value' => 'Assignment Type',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            102 => array(
                'id' => 103,
                'email_notification_type_id' => 23,
                'replace_string' => '{candidateScheduleAssigneeName}',
                'replace_value' => 'Assigned Employee Name',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            103 => array(
                'id' => 104,
                'email_notification_type_id' => 24,
                'replace_string' => '{candidateScheduleAssigneeName}',
                'replace_value' => 'Un-assigned Employee Name',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            104 => array(
                'id' => 105,
                'email_notification_type_id' => 25,
                'replace_string' => '{candidateScheduleAssigneeName}',
                'replace_value' => 'Assigned Employee Name',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            105 => array(
                'id' => 106,
                'email_notification_type_id' => 28,
                'replace_string' => '{candidateScheduleAssigneeName}',
                'replace_value' => 'Submitted Employee Name',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            106 => array(
                'id' => 107,
                'email_notification_type_id' => 23,
                'replace_string' => '{candidateScheduleShiftStartTime}',
                'replace_value' => 'Candidate schedule shift start time',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            107 => array(
                'id' => 108,
                'email_notification_type_id' => 23,
                'replace_string' => '{candidateScheduleShiftEndTime}',
                'replace_value' => 'Candidate schedule shift end time',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            108 => array(
                'id' => 109,
                'email_notification_type_id' => 24,
                'replace_string' => '{candidateScheduleShiftStartTime}',
                'replace_value' => 'Candidate schedule shift start time',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            109 => array(
                'id' => 110,
                'email_notification_type_id' => 24,
                'replace_string' => '{candidateScheduleShiftEndTime}',
                'replace_value' => 'Candidate schedule shift end time',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            110 => array(
                'id' => 111,
                'email_notification_type_id' => 25,
                'replace_string' => '{candidateScheduleShiftStartTime}',
                'replace_value' => 'Candidate schedule shift start time',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            111 => array(
                'id' => 112,
                'email_notification_type_id' => 25,
                'replace_string' => '{candidateScheduleShiftEndTime}',
                'replace_value' => 'Candidate schedule shift end time',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            112 => array(
                'id' => 113,
                'email_notification_type_id' => 19,
                'replace_string' => '{employeeName}',
                'replace_value' => 'Employee Name',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            113 => array(
                'id' => 114,
                'email_notification_type_id' => 19,
                'replace_string' => '{employeeNumber}',
                'replace_value' => 'Employee Number',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            114 => array(
                'id' => 115,
                'email_notification_type_id' => 19,
                'replace_string' => '{payperiodDetails}',
                'replace_value' => 'Payperiod Details',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            115 => array(
                'id' => 116,
                'email_notification_type_id' => 19,
                'replace_string' => '{clientDetails}',
                'replace_value' => 'Client Details',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            116 => array(
                'id' => 117,
                'email_notification_type_id' => 19,
                'replace_string' => '{deadlineDate}',
                'replace_value' => 'Deadline Date',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            117 => array(
                'id' => 118,
                'email_notification_type_id' => 19,
                'replace_string' => '{deadlineTime}',
                'replace_value' => 'Deadline Time',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            118 => array(
                'id' => 119,
                'email_notification_type_id' => 20,
                'replace_string' => '{employeeName}',
                'replace_value' => 'Employee Name',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            119 => array(
                'id' => 120,
                'email_notification_type_id' => 20,
                'replace_string' => '{employeeNumber}',
                'replace_value' => 'Employee Number',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            120 => array(
                'id' => 121,
                'email_notification_type_id' => 20,
                'replace_string' => '{payperiodDetails}',
                'replace_value' => 'Payperiod Details',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            121 => array(
                'id' => 122,
                'email_notification_type_id' => 20,
                'replace_string' => '{clientDetails}',
                'replace_value' => 'Client Details',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            122 => array(
                'id' => 123,
                'email_notification_type_id' => 20,
                'replace_string' => '{deadlineDate}',
                'replace_value' => 'Deadline Date',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            123 => array(
                'id' => 124,
                'email_notification_type_id' => 20,
                'replace_string' => '{deadlineTime}',
                'replace_value' => 'Deadline Time',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            124 => array(
                'id' => 125,
                'email_notification_type_id' => 21,
                'replace_string' => '{employeeName}',
                'replace_value' => 'Employee Name',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            125 => array(
                'id' => 126,
                'email_notification_type_id' => 21,
                'replace_string' => '{employeeNumber}',
                'replace_value' => 'Employee Number',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            126 => array(
                'id' => 127,
                'email_notification_type_id' => 21,
                'replace_string' => '{payperiodDetails}',
                'replace_value' => 'Payperiod Details',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            127 => array(
                'id' => 128,
                'email_notification_type_id' => 21,
                'replace_string' => '{clientDetails}',
                'replace_value' => 'Client Details',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            128 => array(
                'id' => 129,
                'email_notification_type_id' => 21,
                'replace_string' => '{deadlineDate}',
                'replace_value' => 'Deadline Date',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            129 => array(
                'id' => 130,
                'email_notification_type_id' => 21,
                'replace_string' => '{deadlineTime}',
                'replace_value' => 'Deadline Time',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            130 => array(
                'id' => 131,
                'email_notification_type_id' => 31,
                'replace_string' => '{scheduledUserName}',
                'replace_value' => 'Scheduled User name',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            131 => array(
                'id' => 132,
                'email_notification_type_id' => 31,
                'replace_string' => '{phoneNumber}',
                'replace_value' => 'Phone number',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            132 => array(
                'id' => 133,
                'email_notification_type_id' => 31,
                'replace_string' => '{bookedDate}',
                'replace_value' => 'Booked Date',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            133 => array(
                'id' => 134,
                'email_notification_type_id' => 32,
                'replace_string' => '{bookingDate}',
                'replace_value' => 'Booking Date',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            134 => array(
                'id' => 135,
                'email_notification_type_id' => 32,
                'replace_string' => '{bookingTime}',
                'replace_value' => 'Booking Time',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            135 => array(
                'id' => 136,
                'email_notification_type_id' => 32,
                'replace_string' => '{location}',
                'replace_value' => 'Location',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            136 => array(
                'id' => 137,
                'email_notification_type_id' => 32,
                'replace_string' => '{serviceName}',
                'replace_value' => 'Service Name',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            137 => array(
                'id' => 138,
                'email_notification_type_id' => 32,
                'replace_string' => '{serviceRate}',
                'replace_value' => 'Service Rate',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            138 => array(
                'id' => 139,
                'email_notification_type_id' => 32,
                'replace_string' => '{officePhoneNumber}',
                'replace_value' => 'Office Phone number',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            139 => array(
                'id' => 140,
                'email_notification_type_id' => 33,
                'replace_string' => '{serviceName}',
                'replace_value' => 'Service Name',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            140 => array(
                'id' => 141,
                'email_notification_type_id' => 33,
                'replace_string' => '{bookingDate}',
                'replace_value' => 'Booking Date',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            141 => array(
                'id' => 142,
                'email_notification_type_id' => 33,
                'replace_string' => '{bookingTime}',
                'replace_value' => 'Booking Time',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            142 => array(
                'id' => 143,
                'email_notification_type_id' => 33,
                'replace_string' => '{location}',
                'replace_value' => 'Location',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            143 => array(
                'id' => 144,
                'email_notification_type_id' => 33,
                'replace_string' => '{officePhoneNumber}',
                'replace_value' => 'Office Phone number',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            144 => array(
                'id' => 145,
                'email_notification_type_id' => 36,
                'replace_string' => '{contractName}',
                'replace_value' => 'Contract Name',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            145 => array(
                'id' => 146,
                'email_notification_type_id' => 36,
                'replace_string' => '{expiryDate}',
                'replace_value' => 'Expiry Date',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            146 => array(
                'id' => 147,
                'email_notification_type_id' => 36,
                'replace_string' => '{contractExpiryDueInDays}',
                'replace_value' => 'Contract Expiry Due In Days',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            147 => array(
                'id' => 148,
                'email_notification_type_id' => 37,
                'replace_string' => '{contractName}',
                'replace_value' => 'Contract Name',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            148 => array(
                'id' => 149,
                'email_notification_type_id' => 37,
                'replace_string' => '{expiryDate}',
                'replace_value' => 'Expiry Date',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            149 => array(
                'id' => 150,
                'email_notification_type_id' => 37,
                'replace_string' => '{contractExpiryDueInDays}',
                'replace_value' => 'Contract Expiry Due In Days',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            150 => array(
                'id' => 151,
                'email_notification_type_id' => 38,
                'replace_string' => '{contractName}',
                'replace_value' => 'Contract Name',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            151 => array(
                'id' => 152,
                'email_notification_type_id' => 38,
                'replace_string' => '{expiryDate}',
                'replace_value' => 'Expiry Date',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            152 => array(
                'id' => 153,
                'email_notification_type_id' => 38,
                'replace_string' => '{contractExpiryDueInDays}',
                'replace_value' => 'Contract Expiry Due In Days',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            153 => array(
                'id' => 154,
                'email_notification_type_id' => 39,
                'replace_string' => '{recruiterFullName}',
                'replace_value' => 'Recruiter FullName',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            154 => array(
                'id' => 155,
                'email_notification_type_id' => 40,
                'replace_string' => '{recruiterFullName}',
                'replace_value' => 'Recruiter FullName',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            155 => array(
                'id' => 156,
                'email_notification_type_id' => 41,
                'replace_string' => '{recruiterFullName}',
                'replace_value' => 'Recruiter FullName',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            156 => array(
                'id' => 157,
                'email_notification_type_id' => 42,
                'replace_string' => '{recruiterFullName}',
                'replace_value' => 'Recruiter FullName',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            157 => array(
                'id' => 158,
                'email_notification_type_id' => 43,
                'replace_string' => '{activationUrl}',
                'replace_value' => 'Activation URL',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            158 => array(
                'id' => 159,
                'email_notification_type_id' => 44,
                'replace_string' => '{activationUrl}',
                'replace_value' => 'Activation URL',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            159 => array(
                'id' => 160,
                'email_notification_type_id' => 46,
                'replace_string' => '{total_score}',
                'replace_value' => 'Score',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            160 => array(
                'id' => 161,
                'email_notification_type_id' => 48,
                'replace_string' => '{candidate}',
                'replace_value' => 'Candidate',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            161 => array(
                'id' => 162,
                'email_notification_type_id' => 40,
                'replace_string' => '{jobCode}',
                'replace_value' => 'Job Code',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            162 => array(
                'id' => 163,
                'email_notification_type_id' => 40,
                'replace_string' => '{jobWage}',
                'replace_value' => 'Job Wage',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            163 => array(
                'id' => 164,
                'email_notification_type_id' => 49,
                'replace_string' => '{jobCode}',
                'replace_value' => 'Job Code',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            164 => array(
                'id' => 165,
                'email_notification_type_id' => 49,
                'replace_string' => '{dueInDays}',
                'replace_value' => 'Due  in days',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            165 => array(
                'id' => 166,
                'email_notification_type_id' => 49,
                'replace_string' => '{dueDate}',
                'replace_value' => 'Job Due Date',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            166 => array(
                'id' => 167,
                'email_notification_type_id' => 43,
                'replace_string' => '{username}',
                'replace_value' => 'User Name',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            167 => array(
                'id' => 168,
                'email_notification_type_id' => 44,
                'replace_string' => '{username}',
                'replace_value' => 'User Name',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
                ),
            168 => array(
                'id' => 169,
                'email_notification_type_id' => 51,
                'replace_string' => '{recruiterFullName}',
                'replace_value' => 'Recruiter FullName',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
                ),
            169 => array(
                'id' => 170,
                'email_notification_type_id' => 52,
                'replace_string' => '{activationUrl}',
                'replace_value' => 'Activation Url',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
                ),
            170 => array(
                'id' => 171,
                'email_notification_type_id' => 53,
                'replace_string' => '{randomPassword}',
                'replace_value' => 'Random Password',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
                ),
            171 => array(
                'id' => 172,
                'email_notification_type_id' => 54,
                'replace_string' => '{courseName}',
                'replace_value' => 'Course Name',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            172 => array(
                'id' => 173,
                'email_notification_type_id' => 55,
                'replace_string' => '{contractName}',
                'replace_value' => 'Contract Name',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            173 => array(
                'id' => 174,
                'email_notification_type_id' => 55,
                'replace_string' => '{subject}',
                'replace_value' => 'Subject',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
                ),
              174 => array(
                'id' => 175,
                'email_notification_type_id' => 65,
                'replace_string' => '{reporterFullName}',
                'replace_value' => 'Reporter full Name',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
                )
        ));
    }
}
