<?php

namespace Modules\Admin\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class LandingPageWidgetLayoutsTableSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        \DB::table('landing_page_widget_layout_details')->delete();
        \DB::table('landing_page_widget_layouts')->delete();

        \DB::table('landing_page_widget_layouts')->insert(array(
            0 => array(
                'id' => 1,
                'name' => 'One Box',
                'no_of_rows' => 1,
                'no_of_columns' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            1 => array(
                'id' => 2,
                'name' => 'Two Box Vertical',
                'no_of_rows' => 1,
                'no_of_columns' => 2,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            2 => array(
                'id' => 3,
                'name' => 'Two Box Horizontal',
                'no_of_rows' => 2,
                'no_of_columns' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            3 => array(
                'id' => 4,
                'name' => 'Three Box Vertical',
                'no_of_rows' => 2,
                'no_of_columns' => 2,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            4 => array(
                'id' => 5,
                'name' => 'Three Box Horizontal',
                'no_of_rows' => 2,
                'no_of_columns' => 2,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            5 => array(
                'id' => 6,
                'name' => 'Four Box',
                'no_of_rows' => 2,
                'no_of_columns' => 2,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            6 => array(
                'id' => 7,
                'name' => 'Five Box Vertical',
                'no_of_rows' => 2,
                'no_of_columns' => 6,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            7 => array(
                'id' => 8,
                'name' => 'Five Box Horizontal',
                'no_of_rows' => 3,
                'no_of_columns' => 2,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            8 => array(
                'id' => 9,
                'name' => 'Six Box Vertical',
                'no_of_rows' => 2,
                'no_of_columns' => 3,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            9 => array(
                'id' => 10,
                'name' => 'Six Box Horizontal',
                'no_of_rows' => 3,
                'no_of_columns' => 2,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            10 => array(
                'id' => 11,
                'name' => 'Seven Box Vertical',
                'no_of_rows' => 2,
                'no_of_columns' => 4,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            11 => array(
                'id' => 12,
                'name' => 'Seven Box Horizontal',
                'no_of_rows' => 3,
                'no_of_columns' => 3,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            )
        ));

        \DB::table('landing_page_widget_layout_details')->insert(array(
            //One Box
            0 => array(
                'landing_page_widget_layout_id' => 1,
                'row_index' => 1,
                'column_index' => 1,
                'rowspan' => 1,
                'colspan' => 2,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            //Two Box Vertical
            1 => array(
                'landing_page_widget_layout_id' => 2,
                'row_index' => 1,
                'column_index' => 1,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            2 => array(
                'landing_page_widget_layout_id' => 2,
                'row_index' => 1,
                'column_index' => 2,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            //Two Box Horizontal
            3 => array(
                'landing_page_widget_layout_id' => 3,
                'row_index' => 1,
                'column_index' => 1,
                'rowspan' => 1,
                'colspan' => 2,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            4 => array(
                'landing_page_widget_layout_id' => 3,
                'row_index' => 2,
                'column_index' => 1,
                'rowspan' => 1,
                'colspan' => 2,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            //Three Box Vertical
            5 => array(
                'landing_page_widget_layout_id' => 4,
                'row_index' => 1,
                'column_index' => 1,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            6 => array(
                'landing_page_widget_layout_id' => 4,
                'row_index' => 1,
                'column_index' => 2,
                'rowspan' => 2,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            7 => array(
                'landing_page_widget_layout_id' => 4,
                'row_index' => 2,
                'column_index' => 1,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            //Three Box Horizontal
            8 => array(
                'landing_page_widget_layout_id' => 5,
                'row_index' => 1,
                'column_index' => 1,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            9 => array(
                'landing_page_widget_layout_id' => 5,
                'row_index' => 1,
                'column_index' => 2,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            10 => array(
                'landing_page_widget_layout_id' => 5,
                'row_index' => 2,
                'column_index' => 1,
                'rowspan' => 1,
                'colspan' => 2,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            //Four Box
            11 => array(
                'landing_page_widget_layout_id' => 6,
                'row_index' => 1,
                'column_index' => 1,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            12 => array(
                'landing_page_widget_layout_id' => 6,
                'row_index' => 1,
                'column_index' => 2,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            13 => array(
                'landing_page_widget_layout_id' => 6,
                'row_index' => 2,
                'column_index' => 1,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            14 => array(
                'landing_page_widget_layout_id' => 6,
                'row_index' => 2,
                'column_index' => 2,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            //Five Box Vertical
            15 => array(
                'landing_page_widget_layout_id' => 7,
                'row_index' => 1,
                'column_index' => 1,
                'rowspan' => 1,
                'colspan' => 2,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            16 => array(
                'landing_page_widget_layout_id' => 7,
                'row_index' => 1,
                'column_index' => 2,
                'rowspan' => 1,
                'colspan' => 2,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            17 => array(
                'landing_page_widget_layout_id' => 7,
                'row_index' => 1,
                'column_index' => 3,
                'rowspan' => 1,
                'colspan' => 2,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            18 => array(
                'landing_page_widget_layout_id' => 7,
                'row_index' => 2,
                'column_index' => 1,
                'rowspan' => 1,
                'colspan' => 3,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            19 => array(
                'landing_page_widget_layout_id' => 7,
                'row_index' => 2,
                'column_index' => 2,
                'rowspan' => 1,
                'colspan' => 3,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            //Five Box Horizontal
            20 => array(
                'landing_page_widget_layout_id' => 8,
                'row_index' => 1,
                'column_index' => 1,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            21 => array(
                'landing_page_widget_layout_id' => 8,
                'row_index' => 1,
                'column_index' => 2,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            22 => array(
                'landing_page_widget_layout_id' => 8,
                'row_index' => 2,
                'column_index' => 1,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            23 => array(
                'landing_page_widget_layout_id' => 8,
                'row_index' => 2,
                'column_index' => 2,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            24 => array(
                'landing_page_widget_layout_id' => 8,
                'row_index' => 3,
                'column_index' => 1,
                'rowspan' => 1,
                'colspan' => 2,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            //Six Box Vertical
            25 => array(
                'landing_page_widget_layout_id' => 9,
                'row_index' => 1,
                'column_index' => 1,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            26 => array(
                'landing_page_widget_layout_id' => 9,
                'row_index' => 1,
                'column_index' => 2,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            27 => array(
                'landing_page_widget_layout_id' => 9,
                'row_index' => 1,
                'column_index' => 3,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            28 => array(
                'landing_page_widget_layout_id' => 9,
                'row_index' => 2,
                'column_index' => 1,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            29 => array(
                'landing_page_widget_layout_id' => 9,
                'row_index' => 2,
                'column_index' => 2,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            30 => array(
                'landing_page_widget_layout_id' => 9,
                'row_index' => 2,
                'column_index' => 3,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            //Six Box Horizontal
            31 => array(
                'landing_page_widget_layout_id' => 10,
                'row_index' => 1,
                'column_index' => 1,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            32 => array(
                'landing_page_widget_layout_id' => 10,
                'row_index' => 1,
                'column_index' => 2,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            33 => array(
                'landing_page_widget_layout_id' => 10,
                'row_index' => 2,
                'column_index' => 1,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            34 => array(
                'landing_page_widget_layout_id' => 10,
                'row_index' => 2,
                'column_index' => 2,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            35 => array(
                'landing_page_widget_layout_id' => 10,
                'row_index' => 3,
                'column_index' => 1,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            36 => array(
                'landing_page_widget_layout_id' => 10,
                'row_index' => 3,
                'column_index' => 2,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            //Seven Box Horizontal
            37 => array(
                'landing_page_widget_layout_id' => 12,
                'row_index' => 1,
                'column_index' => 1,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            38 => array(
                'landing_page_widget_layout_id' => 12,
                'row_index' => 1,
                'column_index' => 2,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            39 => array(
                'landing_page_widget_layout_id' => 12,
                'row_index' => 1,
                'column_index' => 3,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            40 => array(
                'landing_page_widget_layout_id' => 12,
                'row_index' => 2,
                'column_index' => 1,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            41 => array(
                'landing_page_widget_layout_id' => 12,
                'row_index' => 2,
                'column_index' => 2,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            42 => array(
                'landing_page_widget_layout_id' => 12,
                'row_index' => 2,
                'column_index' => 3,
                'rowspan' => 1,
                'colspan' => 1,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            43 => array(
                'landing_page_widget_layout_id' => 12,
                'row_index' => 3,
                'column_index' => 1,
                'rowspan' => 1,
                'colspan' => 3,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            //Seven Box Vertical
            44 => array(
                'landing_page_widget_layout_id' => 11,
                'row_index' => 1,
                'column_index' => 1,
                'rowspan' => 1,
                'colspan' => 3,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            45 => array(
                'landing_page_widget_layout_id' => 11,
                'row_index' => 1,
                'column_index' => 2,
                'rowspan' => 1,
                'colspan' => 3,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            46 => array(
                'landing_page_widget_layout_id' => 11,
                'row_index' => 1,
                'column_index' => 3,
                'rowspan' => 1,
                'colspan' => 3,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            47 => array(
                'landing_page_widget_layout_id' => 11,
                'row_index' => 1,
                'column_index' => 4,
                'rowspan' => 1,
                'colspan' => 3,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            48 => array(
                'landing_page_widget_layout_id' => 11,
                'row_index' => 2,
                'column_index' => 1,
                'rowspan' => 1,
                'colspan' => 4,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            49 => array(
                'landing_page_widget_layout_id' => 11,
                'row_index' => 2,
                'column_index' => 2,
                'rowspan' => 1,
                'colspan' => 4,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
            50 => array(
                'landing_page_widget_layout_id' => 11,
                'row_index' => 2,
                'column_index' => 3,
                'rowspan' => 1,
                'colspan' => 4,
                'created_at' => '2017-12-27 06:05:41',
                'updated_at' => '2017-12-27 06:05:41',
                'deleted_at' => null,
            ),
        ));
    }

}
