<?php

namespace Modules\Admin\Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class NotificationTypeTableSeeder extends Seeder
{

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('email_notification_types')->delete();

        \DB::table('email_notification_types')->insert(array(
            0 => array(
                'id' => 1,
                'type' => 'client_concern',
                'display_name' => 'Client Concern',
                'customer_based' => 1,
                'requester_based' => 0,
                'created_at' => '2019-05-21 06:04:47',
                'updated_at' => '2019-05-21 06:04:47',
                'deleted_at' => null,
            ),
            1 => array(
                'id' => 2,
                'type' => 'client_feedback',
                'display_name' => 'Client Feedback',
                'customer_based' => 1,
                'requester_based' => 0,
                'created_at' => '2019-05-21 06:04:47',
                'updated_at' => '2019-05-21 06:04:47',
                'deleted_at' => null,
            ),
            2 => array(
                'id' => 3,
                'type' => 'vehicle_maintenance_due',
                'display_name' => 'Vehicle Maintenance Due',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => '2019-05-21 06:04:47',
                'updated_at' => '2019-05-21 06:04:47',
                'deleted_at' => null,
            ),
            3 => array(
                'id' => 4,
                'type' => 'vehicle_maintenance_critical',
                'display_name' => 'Vehicle Maintenance Critical',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => '2019-05-21 06:04:47',
                'updated_at' => '2019-05-21 06:04:47',
                'deleted_at' => null,
            ),
            4 => array(
                'id' => 5,
                'type' => 'scheduling_request_notification',
                'display_name' => 'Client scheduling request',
                'customer_based' => 1,
                'requester_based' => 0,
                'created_at' => '2019-05-21 06:04:47',
                'updated_at' => '2019-05-21 06:04:47',
                'deleted_at' => null,
            ),
            5 => array(
                'id' => 6,
                'type' => 'scheduling_approved_request_notification',
                'display_name' => 'Client scheduling approved/rejected notification',
                'customer_based' => 1,
                'requester_based' => 0,
                'created_at' => '2019-05-21 06:04:47',
                'updated_at' => '2019-05-21 06:04:47',
                'deleted_at' => null,
            ),
            6 => array(
                'id' => 7,
                'type' => 'scheduling_request_notification_creator',
                'display_name' => 'Client scheduling request user notification',
                'customer_based' => 0,
                'requester_based' => 1,
                'created_at' => '2019-05-21 06:04:47',
                'updated_at' => '2019-05-21 06:04:47',
                'deleted_at' => null,
            ),
            7 => array(
                'id' => 8,
                'type' => 'project_management_task_due_reminder',
                'display_name' => 'Project Management Task Due Reminder',
                'customer_based' => 1,
                'requester_based' => 1,
                'created_at' => '2019-05-21 06:04:47',
                'updated_at' => '2019-05-21 06:04:47',
                'deleted_at' => null,
            ),
            8 => array(
                'id' => 9,
                'type' => 'project_management_status_due_reminder',
                'display_name' => 'Project Management Status Due Reminder',
                'customer_based' => 1,
                'requester_based' => 1,
                'created_at' => '2019-05-21 06:04:47',
                'updated_at' => '2019-05-21 06:04:47',
                'deleted_at' => null,
            ),
            9 => array(
                'id' => 10,
                'type' => 'client_onboarding_status_due_reminder',
                'display_name' => 'Client Onboarding Status Due Reminder',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            10 => array(
                'id' => 11,
                'type' => 'client_onboarding_task_assigned',
                'display_name' => 'Client Onboarding Task Assigned',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            11 => array(
                'id' => 12,
                'type' => 'project_management_task_created',
                'display_name' => 'Project Management Create Task',
                'customer_based' => 1,
                'requester_based' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            12 => array(
                'id' => 13,
                'type' => 'project_management_task_deleted',
                'display_name' => 'Project Management Delete Task',
                'customer_based' => 1,
                'requester_based' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            13 => array(
                'id' => 14,
                'type' => 'user_certificate_expiry_notification_reminder_1',
                'display_name' => 'Document Expiry Email Remainder 1',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            14 => array(
                'id' => 15,
                'type' => 'user_certificate_expiry_notification_reminder_2',
                'display_name' => 'Document Expiry Email Remainder 2',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            15 => array(
                'id' => 16,
                'type' => 'user_certificate_expiry_notification_reminder_3',
                'display_name' => 'Document Expiry Email Remainder 3',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            16 => array(
                'id' => 17,
                'type' => 'document_expiry_report_notification',
                'display_name' => 'Document Expiry Report Notification',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            17 => array(
                'id' => 18,
                'type' => 'expense_approve_notification_remainder',
                'display_name' => 'Expense Approval Remainder Notification',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            18 => array(
                'id' => 19,
                'type' => 'time_sheet_approve_notification_mail_1',
                'display_name' => 'Timesheet Approval Remainder Email 1',
                'customer_based' => 1,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            19 => array(
                'id' => 20,
                'type' => 'time_sheet_approve_notification_mail_2',
                'display_name' => 'Timesheet Approval Remainder Email 2',
                'customer_based' => 1,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            20 => array(
                'id' => 21,
                'type' => 'time_sheet_approve_notification_mail_3',
                'display_name' => 'Timesheet Approval Remainder Email 3',
                'customer_based' => 1,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            21 => array(
                'id' => 22,
                'type' => 'time_sheet_approve_notification_mail_4',
                'display_name' => 'Timesheet Approval Remainder Email 4',
                'customer_based' => 1,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => '2021-01-22 07:47:28',

            ),
            22 => array(
                'id' => 23,
                'type' => 'candidate_schedule_employee_assigned',
                'display_name' => 'Candidate Schedule Employee Assigned',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            23 => array(
                'id' => 24,
                'type' => 'candidate_schedule_employee_unassigned',
                'display_name' => 'Candidate Schedule Employee Unassigned',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            24 => array(
                'id' => 25,
                'type' => 'candidate_schedule_shift_removal',
                'display_name' => 'Candidate Schedule Shift Removed',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            25 => array(
                'id' => 26,
                'type' => 'cglmeet_scheduling_request_notification',
                'display_name' => 'CGL Meet scheduling request',
                'customer_based' => 0,
                'requester_based' => 1,
                'created_at' => '2019-05-21 06:04:47',
                'updated_at' => '2019-05-21 06:04:47',
                'deleted_at' => null,
            ),
            26 => array(
                'id' => 27,
                'type' => 'cglmeet_scheduling_cancelled_notification',
                'display_name' => 'CGL Meet scheduling cancellation',
                'customer_based' => 0,
                'requester_based' => 1,
                'created_at' => '2019-05-21 06:04:47',
                'updated_at' => '2019-05-21 06:04:47',
                'deleted_at' => null,
            ),
            27 => array(
                'id' => 28,
                'type' => 'candidate_open_shift_notification',
                'display_name' => 'Candidate Open Shift Notification',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            28 => array(
                'id' => 29,
                'type' => 'uniform_schedule_confirmation',
                'display_name' => 'Uniform appointment schedule confirmation',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            29 => array(
                'id' => 30,
                'type' => 'uniform_reschedule_confirmation',
                'display_name' => 'Uniform appointment reschedule confirmation',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            30 => array(
                'id' => 31,
                'type' => 'daily_healthscreen_report',
                'display_name' => 'Daily Health Screen Report',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            31 => array(
                'id' => 32,
                'type' => 'ids_scheduling_booking',
                'display_name' => 'IDS Scheduling Booking',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            32 => array(
                'id' => 33,
                'type' => 'ids_rescheduling',
                'display_name' => 'IDS Rescheduling',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            33 => array(
                'id' => 34,
                'type' => 'ids_booking_cancellation',
                'display_name' => 'IDS Booking Cancellation',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            34 => array(
                'id' => 35,
                'type' => 'uniform_schedule_info',
                'display_name' => 'Uniform schedule info',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            35 => array(
                'id' => 36,
                'type' => 'contract_expiry_remainder_mail_1',
                'display_name' => 'Contract Expiry Reminder Email 1',
                'customer_based' => 1,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            36 => array(
                'id' => 37,
                'type' => 'contract_expiry_remainder_mail_2',
                'display_name' => 'Contract Expiry Reminder Email 2',
                'customer_based' => 1,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            37 => array(
                'id' => 38,
                'type' => 'contract_expiry_remainder_mail_3',
                'display_name' => 'Contract Expiry Reminder Email 3',
                'customer_based' => 1,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            38 =>
            array(
                'id' => 39,
                'type' => 'rejection_notes_notification_mail',
                'display_name' => 'Rejection Note Notification Mail',
                'customer_based' => 1,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            39 =>
            array(
                'id' => 40,
                'type' => 'select_interview_notification_mail',
                'display_name' => 'Select Interview Notification Mail',
                'customer_based' => 1,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            40 =>
            array(
                'id' => 41,
                'type' => 'reject_for_role_notification_mail',
                'display_name' => 'Rejection For Role Notification Mail',
                'customer_based' => 1,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            41 =>
            array(
                'id' => 42,
                'type' => 'begin_onboarding_notification_mail',
                'display_name' => 'Begin Onboarding Notification Mail',
                'customer_based' => 1,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            42 =>
            array(
                'id' => 43,
                'type' => 'rec_candidate_password_reset',
                'display_name' => 'Candidate Password Reset Mail',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            43 =>
            array(
                'id' => 44,
                'type' => 'rec_candidate_register_email_script',
                'display_name' => 'Candidate Register Email',
                'customer_based' => 1,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            44 =>
            array(
                'id' => 45,
                'type' => 'rec_candidate_login_remainder',
                'display_name' => 'Candidate Login Remainder Email',
                'customer_based' => 1,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            45 =>
            array(
                'id' => 46,
                'type' => 'rec_criteria_threshold_mail',
                'display_name' => 'Match Score Criteria Threshold Email',
                'customer_based' => 1,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),

            46 =>
            array(
                'id' => 47,
                'type' => 'rec_uniform_shipment_mail',
                'display_name' => 'Uniform Shipment Email',
                'customer_based' => 1,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            47 =>
            array(
                'id' => 48,
                'type' => 'rec_candidate_application_process_completed',
                'display_name' => 'Application Process Completed-Recruiter Mail',
                'customer_based' => 1,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            48 =>
            array(
                'id' => 49,
                'type' => 'onboarding_deadline_remainder',
                'display_name' => 'Onboarding Deadline Remainder',
                'customer_based' => 1,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            49 =>
            array(
                'id' => 50,
                'type' => 'rec_candidate_application_process_completed_candidate',
                'display_name' => 'Application Process Completed-Candidate Mail',
                'customer_based' => 1,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            50 =>
            array(
                'id' => 51,
                'type' => 'rec_candidate_application_evaluation_acknowledgement',
                'display_name' => 'Application Evaluation Acknowledgement Mail',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            51 => array(
                'id' => 52,
                'type' => 'osgc_user_registration',
                'display_name' => 'OSGC User Registration',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            52 => array(
                'id' => 53,
                'type' => 'osgc_reset_password',
                'display_name' => 'OSGC Reset Password',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            53 => array(
                'id' => 54,
                'type' => 'osgc_course_certificate',
                'display_name' => 'OSGC Course Certificate',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            54 => array(
                'id' => 55,
                'type' => 'whistle_blower_alert_email',
                'display_name' => 'Employee Whistle Blower Alert Mail',
                'customer_based' => 1,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            55 => array(
                'id' => 56,
                'type' => 'employee_feedback_notification_email',
                'display_name' => 'Employee Feedback Submission',
                'customer_based' => 0,
                'requester_based' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            56 => array(
                'id' => 57,
                'type' => 'ids_scheduling_refund',
                'display_name' => 'IDS Scheduling Refund',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            57 => array(
                'id' => 58,
                'type' => 'ids_payment_incomplete',
                'display_name' => 'IDS Payment Incomplete',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            58 => array(
                'id' => 59,
                'type' => 'qr_patrol_daily_activity_report',
                'display_name' => 'Daily Activity Report (Qr patrol)',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            59 => array(
                'id' => 60,
                'type' => 'uniform_order_returned',
                'display_name' => 'Uniform Order Returned',
                'customer_based' => 0,
                'requester_based' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            60 => array(
                'id' => 61,
                'type' => 'uniform_order_received',
                'display_name' => 'Uniform Order Received',
                'customer_based' => 0,
                'requester_based' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            61 => array(
                'id' => 62,
                'type' => 'uniform_order_shipped',
                'display_name' => 'Uniform Order Shipped',
                'customer_based' => 0,
                'requester_based' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            62 => array(
                'id' => 63,
                'type' => 'uniform_order_cancelled',
                'display_name' => 'Uniform Order Cancelled',
                'customer_based' => 0,
                'requester_based' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            63 => array(
                'id' => 64,
                'type' => 'uniform_order_delivered',
                'display_name' => 'Uniform Order Delivered',
                'customer_based' => 0,
                'requester_based' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ),
            64 => array(
                'id' => 65,
                'type' => 'uniform_ordered',
                'display_name' => 'Uniform Ordered',
                'customer_based' => 0,
                'requester_based' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => '2021-06-22 06:08:04',
            ),
             65 => array(
                'id' => 66,
                'type' => 'incident_amendment_notification',
                'display_name' => 'Incident Amendment',
                'customer_based' => 1,
                'requester_based' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
             ),
               66 => array(
                'id' => 67,
                'type' => 'ids_remainder_email',
                'display_name' => 'IDS  Remainder Email',
                'customer_based' => 0,
                'requester_based' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
               ),
             67 => array(
                'id' => 68,
                'type' => 'employee_timesheet_approval_mail_alert',
                'display_name' => 'Employee Timesheet Approval Mail Alert',
                'customer_based' => 0,
                'requester_based' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
             ),
             68 => array(
                'id' => 69,
                'type' => 'expense_claim_rejection_email',
                'display_name' => 'Expense Claim Rejection Email',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
             ),
             69 => array(
                'id' => 70,
                'type' => 'expense_claim_approval_email',
                'display_name' => 'Expense Claim Approval Email',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
             ),
             70 => array(
                'id' => 71,
                'type' => 'expense_claim_reimbursement_approval_email',
                'display_name' => 'Expense Claim Reimbursement Approval Email',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
             ),
             71 => array(
                'id' => 72,
                'type' => 'expense_claim_submission_email',
                'display_name' => 'Expense Claim Submission Email',
                'customer_based' => 0,
                'requester_based' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
             )
        ));
    }
}
