<?php

namespace Modules\Admin\Database\Seeders;

use Illuminate\Database\Seeder;

class SampleIncidentSubjectsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('sample_incident_subjects')->delete();

        \DB::table('sample_incident_subjects')->insert(array(
            0 => array(
                'id' => 1,
                'subject_id' => 82,
                'subject' => 'Access card lost/found/damaged',
                'category_id' => '2',
                'priority_id' => 2,
                'incident_response_time' => 360,
                'sop' => 'Please proceed as per the post order.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ),
            1 => array(
                'id' => 2,
                'subject_id' => 72,
                'subject' => 'Damaged caused to buildings',
                'category_id' => '7',
                'priority_id' => 2,
                'incident_response_time' => 360,
                'sop' => 'Please proceed as per the post order.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ),
            2 => array(
                'id' => 3,
                'subject_id' => 80,
                'subject' => 'Elevator entrapment',
                'category_id' => '1',
                'priority_id' => 3,
                'incident_response_time' => 120,
                'sop' => 'Please proceed as per the post order.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ),
            3 => array(
                'id' => 4,
                'subject_id' => 70,
                'subject' => 'Fire, Life Safety Equipment deficiencies',
                'category_id' => '3',
                'priority_id' => 1,
                'incident_response_time' => 360,
                'sop' => 'Please proceed as per the post order.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ),
            4 => array(
                'id' => 5,
                'subject_id' => 74,
                'subject' => 'Fire/Police site visits',
                'category_id' => '3',
                'priority_id' => 3,
                'incident_response_time' => 120,
                'sop' => 'Please proceed as per the post order.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ),
            5 => array(
                'id' => 6,
                'subject_id' => 66,
                'subject' => 'Hazardous Chemicals',
                'category_id' => '6',
                'priority_id' => 3,
                'incident_response_time' => 120,
                'sop' => 'Please proceed as per the post order.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ),
            6 => array(
                'id' => 7,
                'subject_id' => 73,
                'subject' => 'Hazardous conditions',
                'category_id' => '6',
                'priority_id' => 2,
                'incident_response_time' => 360,
                'sop' => 'Please proceed as per the post order.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ),
            7 => array(
                'id' => 8,
                'subject_id' => 81,
                'subject' => 'Keys lost/found/damages',
                'category_id' => '2',
                'priority_id' => 3,
                'incident_response_time' => 120,
                'sop' => 'Please proceed as per the post order.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ),
            8 => array(
                'id' => 9,
                'subject_id' => 78,
                'subject' => 'Lost and found articles',
                'category_id' => '2',
                'priority_id' => 1,
                'incident_response_time' => 360,
                'sop' => 'Please proceed as per the post order.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ),
            9 => array(
                'id' => 10,
                'subject_id' => 76,
                'subject' => 'Media activity on site',
                'category_id' => '8',
                'priority_id' => 2,
                'incident_response_time' => 360,
                'sop' => 'Please proceed as per the post order.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ),
            10 => array(
                'id' => 11,
                'subject_id' => 71,
                'subject' => 'Medical Emergency',
                'category_id' => '4',
                'priority_id' => 3,
                'incident_response_time' => 120,
                'sop' => 'Please proceed as per the post order.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ),
            11 => array(
                'id' => 12,
                'subject_id' => 83,
                'subject' => 'Other major security deficiencies',
                'category_id' => '8',
                'priority_id' => 1,
                'incident_response_time' => 360,
                'sop' => 'Please proceed as per the post order.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ),
            12 => array(
                'id' => 13,
                'subject_id' => 79,
                'subject' => 'Parking incidents',
                'category_id' => '8',
                'priority_id' => 1,
                'incident_response_time' => 360,
                'sop' => 'Please proceed as per the post order.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ),
            13 => array(
                'id' => 14,
                'subject_id' => 68,
                'subject' => 'Plumbing, Electrical, maintenance conditions',
                'category_id' => '1',
                'priority_id' => 1,
                'incident_response_time' => 120,
                'sop' => 'Please proceed as per the post order.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ),
            14 => array(
                'id' => 15,
                'subject_id' => 77,
                'subject' => 'Protest activities',
                'category_id' => '8',
                'priority_id' => 3,
                'incident_response_time' => 120,
                'sop' => 'Please proceed as per the post order.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ),
            15 => array(
                'id' => 16,
                'subject_id' => 69,
                'subject' => 'Slips, Trips & Falls',
                'category_id' => '5',
                'priority_id' => 3,
                'incident_response_time' => 120,
                'sop' => 'Please proceed as per the post order.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ),
            16 => array(
                'id' => 17,
                'subject_id' => 65,
                'subject' => 'Suspicious Activity / Intruder',
                'category_id' => '7',
                'priority_id' => 3,
                'incident_response_time' => 120,
                'sop' => 'Please proceed as per the post order.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ),
            17 => array(
                'id' => 18,
                'subject_id' => 67,
                'subject' => 'Theft/Break-Ins/Vandalism',
                'category_id' => '7',
                'priority_id' => 3,
                'incident_response_time' => 120,
                'sop' => 'Please proceed as per the post order.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ),
            18 => array(
                'id' => 19,
                'subject_id' => 75,
                'subject' => 'Windows, outside door left open after-hours',
                'category_id' => '8',
                'priority_id' => 1,
                'incident_response_time' => 360,
                'sop' => 'Please proceed as per the post order.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ),
            19 => array(
                'id' => 20,
                'subject_id' => 84,
                'subject' => 'Active Alarm',
                'category_id' => '3',
                'priority_id' => 3,
                'incident_response_time' => 120,
                'sop' => 'Please proceed as per the post order.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ),
            20 => array(
                'id' => 21,
                'subject_id' => 85,
                'subject' => 'Safety Hazards',
                'category_id' => '6',
                'priority_id' => 2,
                'incident_response_time' => 360,
                'sop' => 'Please proceed as per the post order.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ),

        ));

    }
}
