<?php

namespace Modules\CapacityTool\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class CapacityToolQuestionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        // $this->call("OthersTableSeeder");
        \DB::table('capacity_tool_questions')->delete();
        \DB::table('capacity_tool_questions')->insert([

            0 => [
                'id' => 1,
                'question' => 'Name',
                'answer_type' => null,
                'is_parent' => '0',
                'parent_id' => null,
                'show_child_value' => null,
                'tooltip' => '',
                'field_type' => 'text',
                'order' => 1,
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            1 => [
                'id' => 2,
                'question' => 'Was this task related to a particular client?',
                'answer_type' => 'Modules\Admin\Models\YesOrNoLookup',
                'is_parent' => '0',
                'parent_id' => null,
                'show_child_value' => null,
                'tooltip' => '',
                'field_type' => 'dropdown',
                'order' => 3,
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            2 => [
                'id' => 3,
                'question' => 'Which project number?',
                'answer_type' => 'Modules\Admin\Models\Customer',
                'is_parent' => '1',
                'parent_id' => 2,
                'show_child_value' => 1,
                'tooltip' => '',
                'field_type' => 'project_name',
                'order' => 4,
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],

            3 => [
                'id' => 4,
                'question' => 'What task did you perform?',
                'answer_type' => null,
                'is_parent' => '0',
                'parent_id' => null,
                'show_child_value' => null,
                'tooltip' => '',
                'field_type' => 'text',
                'order' => 2,
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            4 => [
                'id' => 5,
                'question' => 'How would you classify the work you did based on the following classifications?',
                'answer_type' => 'Modules\Admin\Models\CapacityToolWorkClassificationAreaLookup',
                'is_parent' => '0',
                'parent_id' => null,
                'show_child_value' => null,
                'tooltip' => '',
                'field_type' => 'dropdown',
                'order' => 5,
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            5 => [
                'id' => 6,
                'question' => 'Was this a one time project with start/end date or recurring task?',
                'answer_type' => 'Modules\Admin\Models\CapacityToolTaskTypeLookup',
                'is_parent' => '0',
                'parent_id' => null,
                'show_child_value' => null,
                'tooltip' => '',
                'field_type' => 'dropdown',
                'order' => 6,
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            6 => [
                'id' => 7,
                'question' => 'Are you recording a task that is less than 7 days in duration (ie. A one time task that took place on a certain day)?',
                'answer_type' => 'Modules\Admin\Models\YesOrNoLookup',
                'is_parent' => '1',
                'parent_id' => '6',
                'show_child_value' => '1', //One Time
                'tooltip' => '',
                'field_type' => 'dropdown',
                'order' => 7,
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            7 => [
                'id' => 8,
                'question' => 'What day did you perform this task?',
                'answer_type' => null,
                'is_parent' => '1',
                'parent_id' => '7',
                'show_child_value' => '1',
                'tooltip' => '',
                'field_type' => 'datepicker',
                'order' => 8,
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            8 => [
                'id' => 9,
                'question' => 'How many hours did you spend on the task?',
                'answer_type' => null,
                'is_parent' => '1',
                'parent_id' => '7',
                'show_child_value' => '1',
                'tooltip' => '',
                'field_type' => 'hours',
                'order' => 9,
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            9 => [
                'id' => 10,
                'question' => 'If this was a project longer than 7 days, when did the project start?',
                'answer_type' => null,
                'is_parent' => '1',
                'parent_id' => '7',
                'show_child_value' => '2',
                'tooltip' => '',
                'field_type' => 'datepicker',
                'order' => 10,
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            10 => [
                'id' => 11,
                'question' => 'When did you (or expect to) complete the project?',
                'answer_type' => null,
                'is_parent' => '1',
                'parent_id' => '7',
                'show_child_value' => '2',
                'tooltip' => '',
                'field_type' => 'datepicker',
                'order' => 11,
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            11 => [
                'id' => 12,
                'question' => 'How many hours did it take to complete the task if one time? If recurring, how long does it usually take?',
                'answer_type' => null,
                'is_parent' => '1',
                'parent_id' => '6',
                'show_child_value' => '2',
                'tooltip' => '',
                'field_type' => 'hours',
                'order' => 12,
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            12 => [
                'id' => 13,
                'question' => 'How many hours did it take to complete the task if one time? If recurring, how long does it usually take?',
                'answer_type' => null,
                'is_parent' => '1',
                'parent_id' => '7',
                'show_child_value' => '2',
                'tooltip' => '',
                'field_type' => 'hours',
                'order' => 13,
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],


            13 => [
                'id' => 14,
                'question' => 'How would you classify the frequency of the task?',
                'answer_type' => 'Modules\Admin\Models\CapacityToolTaskFrequencyLookup',
                'is_parent' => '0',
                'parent_id' => null,
                'show_child_value' => null,
                'tooltip' => 'Reminder - If your task is "recurring", then by definition it cannot be Ad Hoc - it must be daily, weekly, monthly, etc. If your task is "one-time", then by definition, it must be "ad-hoc" only. It cannot be daily, weekly etc.',
                'field_type' => 'dropdown',
                'order' => 14,
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            14 => [
                'id' => 15,
                'question' => 'Did you accomplish the objective you set out to achieve?',
                'answer_type' => 'Modules\Admin\Models\CapacityToolObjectiveLookup',
                'is_parent' => '0',
                'parent_id' => null,
                'show_child_value' => null,
                'tooltip' => 'If your task is recurring, then by defintion - the task will always be "ongoing". If your task is "one-time", then you have either "acheived", "did not acheive", or are "pending outcome". A one time task cannot be labelled "ongoing".',
                'field_type' => 'dropdown',
                'order' => 15,
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            15 => [
                'id' => 16,
                'question' => 'Please briefly outline the outcome of your efforts',
                'answer_type' => null,
                'is_parent' => '0',
                'parent_id' => null,
                'show_child_value' => null,
                'tooltip' => '',
                'field_type' => 'textarea',
                'order' => 16,
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            16 => [
                'id' => 17,
                'question' => 'What strategic goal was your effort aligned to?',
                'answer_type' => 'Modules\Admin\Models\CapacityToolSkillTypeLookup',
                'is_parent' => '0',
                'parent_id' => null,
                'show_child_value' => null,
                'tooltip' => '',
                'field_type' => 'dropdown',
                'order' => 17,
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],            
            17 => [
                'id' => 18,
                'question' => 'How would you classify your current efforts and outcomes you acheived as it relates to your job?',
                'answer_type' => 'Modules\Admin\Models\CapacityToolStatusLookup',
                'is_parent' => '0',
                'parent_id' => null,
                'show_child_value' => null,
                'tooltip' => '',
                'field_type' => 'dropdown',
                'order' => 18,
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            18 => [
                'id' => 19,
                'question' => 'What role did you play to complete this task?',
                'answer_type' => 'Modules\Admin\Models\RoleLookup',
                'is_parent' => '0',
                'parent_id' => null,
                'show_child_value' => null,
                'tooltip' => '',
                'field_type' => 'dropdown',
                'order' => 19,
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
         

        ]);
       
    }
}
