<?php

return [
    'candidate_day_count' => 7,
    'candidate_shift_count' => 6,
    'array_day' => ["Any Day", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    'array_shift' => ["All", "Days", "Afternoons", "Evenings", "Overnight", "Statutory holidays", "Continental (12 Hours Shift)"],
    'array_shift_day' => [0 => "Any Day", 1 => "Sunday", 2 => "Monday", 3 => "Tuesday", 4 => "Wednesday", 5 => "Thursday", 6 => "Friday", 7 => "Saturday"],
    'markers' => env('APP_URL') . '/images/markers',
    'customer_detail_payperiod_paginations' => 8,
    'template_color_precision' => 4,
    'stc_report_color_precision' => 5,
    'incident_attachment_folder' => 'incident_attachment',
    'candidate_employee' => 'candidate_employee',
    'employee_timeoff' => 'employee_timeoff',
    'documents' => 'documents',
    'contracts_attachment' => 'contracts_attachment',
    'guardtour_images_folder' => 'guard_tour',
    'candidate_recruitment' => 'candidate_recruitment',
    'resource_cache_rev' => 200422,
    'map_default_center_lat' => '43.6898335',
    'map_default_center_lng' => '-79.6183305',
    'google_api_key' => env('GOOGLE_MAP_KEY'),
    'google_api_curl_key' => env('GOOGLE_MAP_CURL_KEY'),
    'profilePicPath' => '/images/uploads/',
    'courseImagePath' => '/LearningAndTraining/course_images/',
    'courseFilePath' => '/course_files/',
    'noAvatarImg' => 'no_avatar.jpg',
    'policyPath' => config('app.url') . '/policy_files/',
    'litmos_api_key' => '8640fad4-6d75-4c49-a607-eb2068ad30ad',
    'multiple_fill_id' => 4,
    'called_accepted_shift_id' => 1,
    'colour_yellow' => 'yellow',
    'colour_green' => 'green',
    'colour_red' => 'red',
    'colour_black' => 'black',
    'colour_white' => 'white',
    'candidate_application_folder' => 'candidate_application',
    'rec_candidate_application' => 'rec_candidate_application',
    'mobile_app_version' => 3,
    'coo_email' => 'balexander@commissionaires-cgl.ca',
    'coo_mail_valid' => false,
    'shift_module_attachment_folder' => 'shift_module_attachment',
    'expense-send-statements' => 'expense-send-statements',
    'post_order_attachment_folder' => 'post_order_attachment',
    'rfp_catalogue_attachment_folder' => 'rfp_catalogue_attachment',
    'firebase_web_token' => 'AIzaSyBwNHEPeO0sLLyKxyIA7vswR4lybj6r8nM',
    'shift_minimum_duration_limit' => 10,
    'client_concern_type' => 1,
    'client_feedback_type' => 2,
    'fever_scan_module' => 'Fever Scan',
    'idsCustomQuestionOther' => 1,
    'vehicle_module_attachment_folder' => 'vehicle_module_attachment',
    'notificationTime' => '09:00',
    'vehicleServiceTime' => '07:50',
    'addVehiclePendingServiceTime' => '08:00',
    'onboardingDeadlineRemainderTime' => '08:30',
    'qr_patrol_attachment_folder' => 'qr_patrol_attachment',
    'vehicle_maintenance_attachment_folder' => 'vehicle_maintenance_attachment',
    'userCertificateExpiryDueReminderEmailTime' => '10:01',
    'ExpenseReminderEmailTime' => '9:01',
    'keymanagement' => 'keymanagement',
    'landingPageInvalidPermissionDisplayMessageText' => "Don't have permission to view",
    'landingPageExceptionCustomErrorMessageText' => "Something went wrong",
    'open_incident_report_status' => 1,
    'closed_incident_report_status' => 3,
    'incident_high_response_time' => 120,
    'incident_medium_response_time' => 360,
    'incident_low_response_time' => 360,
    'room_severity' => [0 => '', 1 => "High", 2 => "Medium", 3 => "Low"],
    'position_availibility' => [null => 'Please select from the dropdown list', '1' => 'I\'m ok to start as a floater/spare until a full time position comes up', '2' => 'I\'m only interested in the position I\'ve applied for'],
    'starting_time' => [null => 'Please select from the dropdown list', "1" => "I could start as soon as possible (less than 1 days notice)", "2" => "I could start with 1-3 days notice", "3" => "I could start with 3 to 5 days notice", "4" => "I need to provide atleast 5 to 10 days notice"],
    'uniform_scheduling_future_days' => 10,
    'uniform_measurement_decimal_points' => ['0.00' => '0', '0.250' => '1/4', '0.500' => '1/2', '0.750' => '3/4', '0.125' => '1/8', '0.375' => '3/8', '0.625' => '5/8', '0.875' => '7/8'],
    'schedule_non_compliance_type' => [1 => "Critically Late", 2 => "Marginally Late", 3 => "On Time", 4 => "Full Shift", 5 => "No Show", 6 => "Critically Early Out", 7 => "Marginally Early Out"],
    'summaryDashboardDataProcessTime' => '00:01',
    'BonusDataProcessTime' => '23:00',
    'summaryDashboardQaPatrolLogProcessTime' => '00:10',
    'kpiCalculationTime' => '01:01',
    'stripe_secret_key' => env('STRIPE_SECRET'),
    'stripe_key' => env('STRIPE_KEY'),
    'ids_stripe_secret_key' => env('IDS_STRIPE_SECRET'),
    'ids_stripe_key' => env('IDS_STRIPE_KEY'),
    'google_recaptcha_key' => env('GOOGLE_RECAPTCHA_KEY'),
    'google_recaptcha_secret' => env('GOOGLE_RECAPTCHA_SECRET'),
    'earned_billing_table_switch_date' => "2021-04-22",
    "earned_billing_table_switch_regular_update_upto_days" => 14,
    'match_type' => [0 => '', 1 => "Yes/No", 2 => "In Year", 3 => "In Percentage", 4 => "In Minutes", 5 => "Text", 6 => "In Value"],
    'rec_selection_status' => [0 => "Rejection Note", 1 => "Selected for Interview", 2 => "Reject for Role", 3 => "Begin Onboarding", 4 => "Pending for Onboarding"],
    'selection_type_mail_arr' => [0 => 'rejection_notes_notification_mail', 1 => 'select_interview_notification_mail', 2 => 'reject_for_role_notification_mail', 3 => 'begin_onboarding_notification_mail'],
    'match_score_color' => [0 => ['upper_limit' => 0, 'color' => 'red', 'fontcolor' => 'white'], 1 => ['upper_limit' => 3, 'color' => 'red', 'fontcolor' => 'white'], 2 => ['upper_limit' => 4, 'color' => 'yellow', 'fontcolor' => 'black'], 3 => ['upper_limit' => 5, 'color' => 'green', 'fontcolor' => 'white']],
    'shipping_status' => [0 => 'Please select status', 1 => 'Order', 2 => 'Shipped', 3 => 'Received'],
    'RecruitmentLoginReminderEmailTime' => '9:02',
    'recruitmentUrl' => env('RECRUITMENT_APP_URL'),
    'rec_training_id' => env('RECRUITMENT_TRAINING_ID'),
    'ip_cam_ms_ip' => env('IP_CAM_MS_IP'),
    'ip_cam_view_path' => env('IP_CAM_VIEW_PATH'),
    'ip_cam_auth_table' => env('IP_CAM_AUTH_TABLE'),
    'ip_cam_api_username' => env('IP_CAM_API_USERNAME'),
    'ip_cam_api_password' => env('IP_CAM_API_PASSWORD'),
    'aws_key' => env('AWS_KEY'),
    'aws_secret' => env('AWS_SECRET'),
    'aws_region' => env('AWS_REGION'),
    'referral' => [1 => 'Google Search', 2 => 'Bing Search', 3 => 'Facebook', 4 => 'Twitter', 5 => 'Word of Mouth', 6 => 'Government of Agency', 7 => 'Employer Referral'],
    'video_post_type' => ['summary' => 'Summary', 'detailed' => 'Detailed'],
    'video_post_file_type' => ['video' => 'Video', 'pdf' => 'PDF'],
    'training_completed_tracking_id' => 21,
    'document_category_id' => env('DOCUMENT_CATEGORY_ID_FOR_RECRUITMENT'),
    'document_name_id' => env('DOCUMENT_NAME_ID_FOR_RECRUITMENT'),
    'ids_refund_not_requested' => 0,
    'ids_refund_requested' => 1,
    'ids_refund_approved' => 2,
    'ids_refund_rejected' => 3,
    'qrPatrolDailyReportTime' => '8:00',
    'editFontIcon'=>'far fa-edit',
    'deleteFontIcon'=>'fas fa-trash',
    'blockFontIcon'=>'fas fa-ban',
    'activateFontIcon'=>'far fa-check-circle'
];

