<?php

namespace Modules\Recruitment\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class RecCandidateScreeningPersonalityTestQuestionOptionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        // $this->call("OthersTableSeeder");
        \DB::connection('mysql_rec')->table('rec_candidate_screening_personality_test_question_options')->delete();

        \DB::connection('mysql_rec')->table('rec_candidate_screening_personality_test_question_options')->insert([
            0 => [
                'id' => 1,
                'question_id' => 1,
                'value' => 'Interact with many, including strangers',
                'option' => 'a',
            ],
            1 => [
                'id' => 2,
                'question_id' => 1,
                'value' => 'Interact with few, known only to you',
                'option' => 'b',
            ],
            2 => [
                'id' => 3,
                'question_id' => 2,
                'value' => 'I need facts about a company before I make an investment.  I do not make speculative bets on companies',
                'option' => 'a',
            ],
            3 => [
                'id' => 4,
                'question_id' => 2,
                'value' => 'I am willing to invest in a stock based on hype and speculation over facts about the company',
                'option' => 'b',
            ],
            4 => [
                'id' => 5,
                'question_id' => 3,
                'value' => 'To daydream and have your head constantly "in the clouds" at a remote security post',
                'option' => 'a',
            ],
            5 => [
                'id' => 6,
                'question_id' => 3,
                'value' => 'To be doing a boring, habitual, repetitive task over and over again at a remote security post',
                'option' => 'b',
            ],
            6 => [
                'id' => 7,
                'question_id' => 4,
                'value' => 'A person who is principled and has high integrity?',
                'option' => 'a',
            ],
            7 => [
                'id' => 8,
                'question_id' => 4,
                'value' => 'A person who goes by what they feel and is guided by emotions?',
                'option' => 'b',
            ],
            8 => [
                'id' => 9,
                'question_id' => 5,
                'value' => 'A convincing argument based on facts',
                'option' => 'a',
            ],
            9 => [
                'id' => 10,
                'question_id' => 5,
                'value' => 'A touching story that appeals to your emotions',
                'option' => 'b',
            ],
            10 => [
                'id' => 11,
                'question_id' => 6,
                'value' => 'Working to a deadline to get the work done (ie. dishes, laundry, cleaning the house)',
                'option' => 'a',
            ],

            11 => [
                'id' => 12,
                'question_id' => 6,
                'value' => 'Being more relaxed and flexible, getting to the work "whenever"',
                'option' => 'b',
            ],
            12 => [
                'id' => 13,
                'question_id' => 7,
                'value' => 'Choose whether to buy the product based on careful analysis around cost, quality, other comparable products, etc',
                'option' => 'a',
            ],
            13 => [
                'id' => 14,
                'question_id' => 7,
                'value' => 'Buy the product based on impulse and how you feel at the moment',
                'option' => 'b',
            ],

            14 => [
                'id' => 15,
                'question_id' => 8,
                'value' => 'Tend to stay late, with increasing energy to stay longer and socialize more',
                'option' => 'a',
            ],
            15 => [
                'id' => 16,
                'question_id' => 8,
                'value' => 'Leave early, feeling like you\'ve spent a lot of energy being at the event',
                'option' => 'b',
            ],
            16 => [
                'id' => 17,
                'question_id' => 9,
                'value' => 'More sensible people',
                'option' => 'a',
            ],
            17 => [
                'id' => 18,
                'question_id' => 9,
                'value' => 'More creative and imaginative people',
                'option' => 'b',
            ],
            18 => [
                'id' => 19,
                'question_id' => 10,
                'value' => 'Are grounded in actual reality - things I can see, hear, taste, touch or smell.  I don\'t think too much about the future',
                'option' => 'a',
            ],

            19 => [
                'id' => 20,
                'question_id' => 10,
                'value' => 'Are possible, things that can change my reality for the better',
                'option' => 'b',
            ],
            20 => [
                'id' => 21,
                'question_id' => 11,
                'value' => 'The person should be prosecuted for theft despite stealing for a good reason (they were hungry).  Let the courts decide their fate',
                'option' => 'a',
            ],
            21 => [
                'id' => 22,
                'question_id' => 11,
                'value' => 'Show compassion to the individual and do not prosecute the individual for theft',
                'option' => 'b',
            ],
            22 => [
                'id' => 23,
                'question_id' => 12,
                'value' => 'Objective - You form an opinion on the individual based on facts you gather in your conversation',
                'option' => 'a',
            ],
            23 => [
                'id' => 24,
                'question_id' => 12,
                'value' => 'Personal - You open up and  bond with the stranger, sharing your feelings and emotions',
                'option' => 'b',
            ],
            24 => [
                'id' => 25,
                'question_id' => 13,
                'value' => 'Punctual - "Always on time"',
                'option' => 'a',
            ],
            25 => [
                'id' => 26,
                'question_id' => 13,
                'value' => 'Leisurely - "Take your time"',
                'option' => 'b',
            ],
            26 => [
                'id' => 27,
                'question_id' => 14,
                'value' => '"I am bothered MORE when things are incomplete versus completed"',
                'option' => 'a',
            ],
            27 => [
                'id' => 28,
                'question_id' => 14,
                'value' => '"I am bothered MORE when things are completed versus incomplete"',
                'option' => 'b',
            ],
            28 => [
                'id' => 29,
                'question_id' => 15,
                'value' => 'Like to keep on top of the latest "gossip" about other people',
                'option' => 'a',
            ],
            29 => [
                'id' => 30,
                'question_id' => 15,
                'value' => 'You don\'t seem too interested in "gossip" about other people and tend to get behind on the latest news',
                'option' => 'b',
            ],
            30 => [
                'id' => 31,
                'question_id' => 16,
                'value' => 'Do it the usual way',
                'option' => 'a',
            ],
            31 => [
                'id' => 32,
                'question_id' => 16,
                'value' => 'Do it your own way',
                'option' => 'b',
            ],
            32 => [
                'id' => 33,
                'question_id' => 17,
                'value' => '"Say what you mean and mean what you say - authenticity is important"',
                'option' => 'a',
            ],
            33 => [
                'id' => 34,
                'question_id' => 17,
                'value' => '"Use examples or comparisons between two things to better explain the material" ',
                'option' => 'b',
            ],
            34 => [
                'id' => 35,
                'question_id' => 18,
                'value' => 'Be honest, even if it may hurt their feelings, it\'s always best to be truthful',
                'option' => 'a',
            ],
            35 => [
                'id' => 36,
                'question_id' => 18,
                'value' => 'Tell a "white lie", it\'s better to protect their feelings than get into an argument over something that may be perceived as hurtful',
                'option' => 'b',
            ],
            36 => [
                'id' => 37,
                'question_id' => 19,
                'value' => 'The person committed the crime and therefore is guilty irrespective of the circumstance regarding their family.  I render a "guilty" verdict',
                'option' => 'a',
            ],
            37 => [
                'id' => 38,
                'question_id' => 19,
                'value' => 'Even though the person broke the law, it was for a good reason.  Therefore, I am not sending this person to jail for doing what I would have done.  I render a "not guilty" verdict',
                'option' => 'b',
            ],
            38 => [
                'id' => 39,
                'question_id' => 20,
                'value' => 'Prefer things to be settled and decided quickly irrespective of the outcome of being declared "Guilty" or "Not Guilty"',
                'option' => 'a',
            ],
            39 => [
                'id' => 40,
                'question_id' => 20,
                'value' => 'Prefer to let things drag out as long as it takes knowing that you may be found "Guilty" or "Not Guility"',
                'option' => 'b',
            ],
            40 => [
                'id' => 41,
                'question_id' => 21,
                'value' => 'Serious and determined',
                'option' => 'a',
            ],
            41 => [
                'id' => 42,
                'question_id' => 21,
                'value' => 'Easy-going',
                'option' => 'b',
            ],
            42 => [
                'id' => 43,
                'question_id' => 22,
                'value' => '"Go with the flow of the interview questions"',
                'option' => 'a',
            ],
            43 => [
                'id' => 44,
                'question_id' => 22,
                'value' => '"Rehearse what you will say prior to the interview"',
                'option' => 'b',
            ],
            44 => [
                'id' => 45,
                'question_id' => 23,
                'value' => '"Facts speak for themselves"',
                'option' => 'a',
            ],
            45 => [
                'id' => 46,
                'question_id' => 23,
                'value' => '"Facts are not necessarily black and white"',
                'option' => 'b',
            ],
            46 => [
                'id' => 47,
                'question_id' => 24,
                'value' => '"Steve Jobs could be annoying"',
                'option' => 'a',
            ],
            47 => [
                'id' => 48,
                'question_id' => 24,
                'value' => '"Steve jobs was fascinating"',
                'option' => 'b',
            ],
            48 => [
                'id' => 49,
                'question_id' => 25,
                'value' => 'A "cool-headed" person',
                'option' => 'a',
            ],
            49 => [
                'id' => 50,
                'question_id' => 25,
                'value' => 'A "warm-hearted" person',
                'option' => 'b',
            ],
            50 => [
                'id' => 51,
                'question_id' => 26,
                'value' => 'A court room judge who renders an "unjust" verdict',
                'option' => 'a',
            ],
            51 => [
                'id' => 52,
                'question_id' => 26,
                'value' => 'A court room judge who renders a "merciless" verdict',
                'option' => 'b',
            ],
            52 => [
                'id' => 53,
                'question_id' => 27,
                'value' => 'Carefully plan out your career options and choose the best career path',
                'option' => 'a',
            ],
            53 => [
                'id' => 54,
                'question_id' => 27,
                'value' => 'Let "fate" and random chance take you to places you may not have anticipated you could go',
                'option' => 'b',
            ],
            54 => [
                'id' => 55,
                'question_id' => 28,
                'value' => 'Buying something',
                'option' => 'a',
            ],
            55 => [
                'id' => 56,
                'question_id' => 28,
                'value' => 'Having the option to buy something',
                'option' => 'b',
            ],
            56 => [
                'id' => 57,
                'question_id' => 29,
                'value' => 'Initiate conversations with strangers',
                'option' => 'a',
            ],
            57 => [
                'id' => 58,
                'question_id' => 29,
                'value' => 'Wait to be approached by strangers',
                'option' => 'b',
            ],
            58 => [
                'id' => 59,
                'question_id' => 30,
                'value' => 'Common sense is rarely questionable - it should be evident to everyone',
                'option' => 'a',
            ],
            59 => [
                'id' => 60,
                'question_id' => 30,
                'value' => 'Common sense is frequently questionable - what is "common sense" to one may not be "common sense" to another',
                'option' => 'b',
            ],
            60 => [
                'id' => 61,
                'question_id' => 31,
                'value' => 'Make themselves useful enough',
                'option' => 'a',
            ],
            61 => [
                'id' => 62,
                'question_id' => 31,
                'value' => 'Exercise their imaginations enough',
                'option' => 'b',
            ],
            62 => [
                'id' => 63,
                'question_id' => 32,
                'value' => 'Standards - using some form of guideline to make your decision',
                'option' => 'a',
            ],
            63 => [
                'id' => 64,
                'question_id' => 32,
                'value' => 'Feelings - "going with your intuition"',
                'option' => 'b',
            ],
            64 => [
                'id' => 65,
                'question_id' => 33,
                'value' => 'Firm than gentle',
                'option' => 'a',
            ],
            65 => [
                'id' => 66,
                'question_id' => 33,
                'value' => 'Gentle than firm',
                'option' => 'b',
            ],
            66 => [
                'id' => 67,
                'question_id' => 34,
                'value' => 'The ability to organize and be methodical',
                'option' => 'a',
            ],
            67 => [
                'id' => 68,
                'question_id' => 34,
                'value' => 'The ability to adapt',
                'option' => 'b',
            ],
            68 => [
                'id' => 69,
                'question_id' => 35,
                'value' => 'Resolute',
                'option' => 'a',
            ],
            69 => [
                'id' => 70,
                'question_id' => 35,
                'value' => 'Open-minded',
                'option' => 'b',
            ],
            70 => [
                'id' => 71,
                'question_id' => 36,
                'value' => 'Stimulate and energize you',
                'option' => 'a',
            ],
            71 => [
                'id' => 72,
                'question_id' => 36,
                'value' => 'Drain you',
                'option' => 'b',
            ],
            72 => [
                'id' => 73,
                'question_id' => 37,
                'value' => 'A practical person',
                'option' => 'a',
            ],
            73 => [
                'id' => 74,
                'question_id' => 37,
                'value' => 'A "day dreamer"',
                'option' => 'b',
            ],
            74 => [
                'id' => 75,
                'question_id' => 38,
                'value' => 'I will form my own conclusion about the guard based on what I observe myself',
                'option' => 'a',
            ],
            75 => [
                'id' => 76,
                'question_id' => 38,
                'value' => 'I will likely be swayed by the 5 guards who have complained and base my decision accordingly',
                'option' => 'b',
            ],
            76 => [
                'id' => 77,
                'question_id' => 39,
                'value' => 'To discuss an issue thoroughly',
                'option' => 'a',
            ],
            77 => [
                'id' => 78,
                'question_id' => 39,
                'value' => 'To arrive at agreement on an issue',
                'option' => 'b',
            ],
            78 => [
                'id' => 79,
                'question_id' => 40,
                'value' => '"With Your Head" - You make rational decisions',
                'option' => 'a',
            ],
            79 => [
                'id' => 80,
                'question_id' => 40,
                'value' => '"With Your Heart" - Emotions influence your decisions',
                'option' => 'b',
            ],
            80 => [
                'id' => 81,
                'question_id' => 41,
                'value' => 'Is structured with a defined start and end date',
                'option' => 'a',
            ],
            81 => [
                'id' => 82,
                'question_id' => 41,
                'value' => 'Is unstructured and done on a casual basis',
                'option' => 'b',
            ],
            82 => [
                'id' => 83,
                'question_id' => 42,
                'value' => 'An orderly schedule with defined shifts',
                'option' => 'a',
            ],
            83 => [
                'id' => 84,
                'question_id' => 42,
                'value' => 'A schedule with random hours that come up from time to time',
                'option' => 'b',
            ],
            84 => [
                'id' => 85,
                'question_id' => 43,
                'value' => 'Many friends with brief contact',
                'option' => 'a',
            ],
            85 => [
                'id' => 86,
                'question_id' => 43,
                'value' => 'A few friends with more lengthy contact',
                'option' => 'b',
            ],
            86 => [
                'id' => 87,
                'question_id' => 44,
                'value' => 'Facts',
                'option' => 'a',
            ],
            87 => [
                'id' => 88,
                'question_id' => 44,
                'value' => 'Principles',
                'option' => 'b',
            ],
            88 => [
                'id' => 89,
                'question_id' => 45,
                'value' => 'Building and selling things',
                'option' => 'a',
            ],
            89 => [
                'id' => 90,
                'question_id' => 45,
                'value' => 'Designing and researching things',
                'option' => 'b',
            ],
            90 => [
                'id' => 91,
                'question_id' => 46,
                'value' => '"You are a very logical person"',
                'option' => 'a',
            ],
            91 => [
                'id' => 92,
                'question_id' => 46,
                'value' => '"You are a very sentimental person"',
                'option' => 'b',
            ],
            92 => [
                'id' => 93,
                'question_id' => 47,
                'value' => 'You are unwavering in your decisions',
                'option' => 'a',
            ],
            93 => [
                'id' => 94,
                'question_id' => 47,
                'value' => 'You are devoted to your decisions',
                'option' => 'b',
            ],
            94 => [
                'id' => 95,
                'question_id' => 48,
                'value' => 'A final and unalterable statement',
                'option' => 'a',
            ],
            95 => [
                'id' => 96,
                'question_id' => 48,
                'value' => 'A tentative and preliminary statement',
                'option' => 'b',
            ],
            96 => [
                'id' => 97,
                'question_id' => 49,
                'value' => 'After making the decision',
                'option' => 'a',
            ],
            97 => [
                'id' => 98,
                'question_id' => 49,
                'value' => 'Before you had to make the decision',
                'option' => 'b',
            ],
            98 => [
                'id' => 99,
                'question_id' => 50,
                'value' => 'Speak easily and at length with strangers',
                'option' => 'a',
            ],
            99 => [
                'id' => 100,
                'question_id' => 50,
                'value' => 'Find little to say to strangers',
                'option' => 'b',
            ],
            100 => [
                'id' => 101,
                'question_id' => 51,
                'value' => 'Past experiences in making a decision',
                'option' => 'a',
            ],
            101 => [
                'id' => 102,
                'question_id' => 51,
                'value' => 'Your "hunch" or "intuition" in making a decision',
                'option' => 'b',
            ],
            102 => [
                'id' => 103,
                'question_id' => 52,
                'value' => 'More practical than creative or imaginitive',
                'option' => 'a',
            ],
            103 => [
                'id' => 104,
                'question_id' => 52,
                'value' => 'More creative and imaginitive than practical',
                'option' => 'b',
            ],
            104 => [
                'id' => 105,
                'question_id' => 53,
                'value' => 'Clear reason and logic towards something',
                'option' => 'a',
            ],
            105 => [
                'id' => 106,
                'question_id' => 53,
                'value' => 'A strong feeling towards something',
                'option' => 'b',
            ],
            106 => [
                'id' => 107,
                'question_id' => 54,
                'value' => 'Fair minded towards someone',
                'option' => 'a',
            ],
            107 => [
                'id' => 108,
                'question_id' => 54,
                'value' => 'Sympathetic towards someone',
                'option' => 'b',
            ],
            108 => [
                'id' => 109,
                'question_id' => 55,
                'value' => 'Make sure things are arranged',
                'option' => 'a',
            ],
            109 => [
                'id' => 110,
                'question_id' => 55,
                'value' => 'Just let things happen',
                'option' => 'b',
            ],
            110 => [
                'id' => 111,
                'question_id' => 56,
                'value' => 'When working with others, things should be negotiable - things should never be set in stone',
                'option' => 'a',
            ],
            111 => [
                'id' => 112,
                'question_id' => 56,
                'value' => 'When working with others, things should be random and circumstantial.  You can\'t predict the future so might as well "go with the flow"',
                'option' => 'b',
            ],
            112 => [
                'id' => 113,
                'question_id' => 57,
                'value' => 'Tend to be the person that hurries to answer the phone',
                'option' => 'a',
            ],
            113 => [
                'id' => 114,
                'question_id' => 57,
                'value' => 'Wait to let someone else answer the phone',
                'option' => 'b',
            ],
            114 => [
                'id' => 115,
                'question_id' => 58,
                'value' => 'A strong sense of reality',
                'option' => 'a',
            ],
            115 => [
                'id' => 116,
                'question_id' => 58,
                'value' => 'A vivid imagination',
                'option' => 'b',
            ],
            116 => [
                'id' => 117,
                'question_id' => 59,
                'value' => '"Black and white"',
                'option' => 'a',
            ],
            117 => [
                'id' => 118,
                'question_id' => 59,
                'value' => '"Shades of grey"',
                'option' => 'b',
            ],
            118 => [
                'id' => 119,
                'question_id' => 60,
                'value' => 'To be too passionate',
                'option' => 'a',
            ],
            119 => [
                'id' => 120,
                'question_id' => 60,
                'value' => 'To be too objective',
                'option' => 'b',
            ],
            120 => [
                'id' => 121,
                'question_id' => 61,
                'value' => 'Hard headed and stubborn',
                'option' => 'a',
            ],
            121 => [
                'id' => 122,
                'question_id' => 61,
                'value' => 'Soft hearted and a pushover',
                'option' => 'b',
            ],
            122 => [
                'id' => 123,
                'question_id' => 62,
                'value' => 'The structured and scheduled',
                'option' => 'a',
            ],
            123 => [
                'id' => 124,
                'question_id' => 62,
                'value' => 'The unstructured and unscheduled',
                'option' => 'b',
            ],
            124 => [
                'id' => 125,
                'question_id' => 63,
                'value' => 'More serious than playful',
                'option' => 'a',
            ],
            125 => [
                'id' => 126,
                'question_id' => 63,
                'value' => 'More playful than serious',
                'option' => 'b',
            ],
            126 => [
                'id' => 127,
                'question_id' => 64,
                'value' => 'Easy to approach',
                'option' => 'a',
            ],
            127 => [
                'id' => 128,
                'question_id' => 64,
                'value' => 'Somewhat reserved',
                'option' => 'b',
            ],
            128 => [
                'id' => 129,
                'question_id' => 65,
                'value' => 'More literal and to the point',
                'option' => 'a',
            ],
            129 => [
                'id' => 130,
                'question_id' => 65,
                'value' => 'More figurative and abstract',
                'option' => 'b',
            ],
            130 => [
                'id' => 131,
                'question_id' => 66,
                'value' => 'Identify with others',
                'option' => 'a',
            ],
            131 => [
                'id' => 132,
                'question_id' => 66,
                'value' => 'Work with others',
                'option' => 'b',
            ],
            132 => [
                'id' => 133,
                'question_id' => 67,
                'value' => 'To be a more reasoned, logical person',
                'option' => 'a',
            ],
            133 => [
                'id' => 134,
                'question_id' => 67,
                'value' => 'To be a more compassionate, empathetic person',
                'option' => 'b',
            ],
            134 => [
                'id' => 135,
                'question_id' => 68,
                'value' => 'Doing things at random without careful thought',
                'option' => 'a',
            ],
            135 => [
                'id' => 136,
                'question_id' => 68,
                'value' => 'Being critical of a person',
                'option' => 'b',
            ],
            136 => [
                'id' => 137,
                'question_id' => 69,
                'value' => 'A planned event',
                'option' => 'a',
            ],
            137 => [
                'id' => 138,
                'question_id' => 69,
                'value' => ' An unplanned event',
                'option' => 'b',
            ],
            138 => [
                'id' => 139,
                'question_id' => 70,
                'value' => 'More deliberate than spontaneous',
                'option' => 'a',
            ],
            139 => [
                'id' => 140,
                'question_id' => 70,
                'value' => ' More spontaneous than deliberate',
                'option' => 'b',
            ],

        ]);
    }
}
